/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface IndividualDetails
 */
export interface IndividualDetails {
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    givenNames?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    nationality?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    placeOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualDetails
     */
    employment?: string;
}

/**
 * Check if a given object implements the IndividualDetails interface.
 */
export function instanceOfIndividualDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IndividualDetailsFromJSON(json: any): IndividualDetails {
    return IndividualDetailsFromJSONTyped(json, false);
}

export function IndividualDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndividualDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'givenNames': !exists(json, 'given_names') ? undefined : json['given_names'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'nationality': !exists(json, 'nationality') ? undefined : json['nationality'],
        'placeOfBirth': !exists(json, 'place_of_birth') ? undefined : json['place_of_birth'],
        'dateOfBirth': !exists(json, 'date_of_birth') ? undefined : json['date_of_birth'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'employment': !exists(json, 'employment') ? undefined : json['employment'],
    };
}

export function IndividualDetailsToJSON(value?: IndividualDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'given_names': value.givenNames,
        'surname': value.surname,
        'nationality': value.nationality,
        'place_of_birth': value.placeOfBirth,
        'date_of_birth': value.dateOfBirth,
        'gender': value.gender,
        'employment': value.employment,
    };
}

