/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface BalanceBalance
 */
export interface BalanceBalance {
    /**
     * 
     * @type {number}
     * @memberof BalanceBalance
     */
    available: number;
    /**
     * 
     * @type {number}
     * @memberof BalanceBalance
     */
    total: number;
}

/**
 * Check if a given object implements the BalanceBalance interface.
 */
export function instanceOfBalanceBalance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "available" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function BalanceBalanceFromJSON(json: any): BalanceBalance {
    return BalanceBalanceFromJSONTyped(json, false);
}

export function BalanceBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'available': json['available'],
        'total': json['total'],
    };
}

export function BalanceBalanceToJSON(value?: BalanceBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'available': value.available,
        'total': value.total,
    };
}

