/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const DashboardTransactionStatuses = {
    Success: 'SUCCESS',
    Pending: 'PENDING',
    Failed: 'FAILED',
    Reversed: 'REVERSED',
    Voided: 'VOIDED'
} as const;
export type DashboardTransactionStatuses = typeof DashboardTransactionStatuses[keyof typeof DashboardTransactionStatuses];


export function DashboardTransactionStatusesFromJSON(json: any): DashboardTransactionStatuses {
    return DashboardTransactionStatusesFromJSONTyped(json, false);
}

export function DashboardTransactionStatusesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardTransactionStatuses {
    return json as DashboardTransactionStatuses;
}

export function DashboardTransactionStatusesToJSON(value?: DashboardTransactionStatuses | null): any {
    return value as any;
}

