/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const DashboardChannelsCategories = {
    Bank: 'BANK',
    CardlessCredit: 'CARDLESS_CREDIT',
    Paylater: 'PAYLATER',
    Cards: 'CARDS',
    Cash: 'CASH',
    DirectDebit: 'DIRECT_DEBIT',
    Ewallet: 'EWALLET',
    Invoice: 'INVOICE',
    QrCode: 'QR_CODE',
    RetailOutlet: 'RETAIL_OUTLET',
    VirtualAccount: 'VIRTUAL_ACCOUNT',
    Xenplatform: 'XENPLATFORM',
    DirectBankTransfer: 'DIRECT_BANK_TRANSFER',
    Other: 'OTHER'
} as const;
export type DashboardChannelsCategories = typeof DashboardChannelsCategories[keyof typeof DashboardChannelsCategories];


export function DashboardChannelsCategoriesFromJSON(json: any): DashboardChannelsCategories {
    return DashboardChannelsCategoriesFromJSONTyped(json, false);
}

export function DashboardChannelsCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardChannelsCategories {
    return json as DashboardChannelsCategories;
}

export function DashboardChannelsCategoriesToJSON(value?: DashboardChannelsCategories | null): any {
    return value as any;
}

