/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface Hateoas
 */
export interface Hateoas {
    /**
     * 
     * @type {string}
     * @memberof Hateoas
     */
    href: string;
    /**
     * 
     * @type {string}
     * @memberof Hateoas
     */
    rel: string;
    /**
     * 
     * @type {string}
     * @memberof Hateoas
     */
    method: string;
}

/**
 * Check if a given object implements the Hateoas interface.
 */
export function instanceOfHateoas(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "href" in value;
    isInstance = isInstance && "rel" in value;
    isInstance = isInstance && "method" in value;

    return isInstance;
}

export function HateoasFromJSON(json: any): Hateoas {
    return HateoasFromJSONTyped(json, false);
}

export function HateoasFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hateoas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': json['href'],
        'rel': json['rel'],
        'method': json['method'],
    };
}

export function HateoasToJSON(value?: Hateoas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'rel': value.rel,
        'method': value.method,
    };
}

