/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicFeeResponse
 */
export interface PublicFeeResponse {
    /**
     * 
     * @type {number}
     * @memberof PublicFeeResponse
     */
    xenditFee: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFeeResponse
     */
    valueAddedTax: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFeeResponse
     */
    xenditWithholdingTax?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFeeResponse
     */
    thirdPartyWithholdingTax?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicFeeResponse
     */
    status?: PublicFeeResponseStatusEnum;
}


/**
 * @export
 */
export const PublicFeeResponseStatusEnum = {
    Pending: 'PENDING',
    Completed: 'COMPLETED',
    Canceled: 'CANCELED',
    Reversed: 'REVERSED'
} as const;
export type PublicFeeResponseStatusEnum = typeof PublicFeeResponseStatusEnum[keyof typeof PublicFeeResponseStatusEnum];


/**
 * Check if a given object implements the PublicFeeResponse interface.
 */
export function instanceOfPublicFeeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "xenditFee" in value;
    isInstance = isInstance && "valueAddedTax" in value;

    return isInstance;
}

export function PublicFeeResponseFromJSON(json: any): PublicFeeResponse {
    return PublicFeeResponseFromJSONTyped(json, false);
}

export function PublicFeeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFeeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xenditFee': json['xendit_fee'],
        'valueAddedTax': json['value_added_tax'],
        'xenditWithholdingTax': !exists(json, 'xendit_withholding_tax') ? undefined : json['xendit_withholding_tax'],
        'thirdPartyWithholdingTax': !exists(json, 'third_party_withholding_tax') ? undefined : json['third_party_withholding_tax'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function PublicFeeResponseToJSON(value?: PublicFeeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xendit_fee': value.xenditFee,
        'value_added_tax': value.valueAddedTax,
        'xendit_withholding_tax': value.xenditWithholdingTax,
        'third_party_withholding_tax': value.thirdPartyWithholdingTax,
        'status': value.status,
    };
}

