/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { Hateoas } from './Hateoas';
import {
    HateoasFromJSON,
    HateoasFromJSONTyped,
    HateoasToJSON,
} from './Hateoas';
import type { PublicTransactionResponse } from './PublicTransactionResponse';
import {
    PublicTransactionResponseFromJSON,
    PublicTransactionResponseFromJSONTyped,
    PublicTransactionResponseToJSON,
} from './PublicTransactionResponse';

/**
 * 
 * @export
 * @interface PublicTransactionsResponse
 */
export interface PublicTransactionsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PublicTransactionsResponse
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<Hateoas>}
     * @memberof PublicTransactionsResponse
     */
    links?: Array<Hateoas>;
    /**
     * 
     * @type {Array<PublicTransactionResponse>}
     * @memberof PublicTransactionsResponse
     */
    data: Array<PublicTransactionResponse>;
}

/**
 * Check if a given object implements the PublicTransactionsResponse interface.
 */
export function instanceOfPublicTransactionsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasMore" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PublicTransactionsResponseFromJSON(json: any): PublicTransactionsResponse {
    return PublicTransactionsResponseFromJSONTyped(json, false);
}

export function PublicTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTransactionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(HateoasFromJSON)),
        'data': ((json['data'] as Array<any>).map(PublicTransactionResponseFromJSON)),
    };
}

export function PublicTransactionsResponseToJSON(value?: PublicTransactionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'has_more': value.hasMore,
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(HateoasToJSON)),
        'data': ((value.data as Array<any>).map(PublicTransactionResponseToJSON)),
    };
}

