/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface RefundsPost404Response
 */
export interface RefundsPost404Response {
    /**
     * 
     * @type {string}
     * @memberof RefundsPost404Response
     */
    errorCode?: RefundsPost404ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof RefundsPost404Response
     */
    message?: string;
}


/**
 * @export
 */
export const RefundsPost404ResponseErrorCodeEnum = {
    DataNotFound: 'DATA_NOT_FOUND'
} as const;
export type RefundsPost404ResponseErrorCodeEnum = typeof RefundsPost404ResponseErrorCodeEnum[keyof typeof RefundsPost404ResponseErrorCodeEnum];


/**
 * Check if a given object implements the RefundsPost404Response interface.
 */
export function instanceOfRefundsPost404Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefundsPost404ResponseFromJSON(json: any): RefundsPost404Response {
    return RefundsPost404ResponseFromJSONTyped(json, false);
}

export function RefundsPost404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundsPost404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function RefundsPost404ResponseToJSON(value?: RefundsPost404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

