/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface RefundsPost503Response
 */
export interface RefundsPost503Response {
    /**
     * 
     * @type {string}
     * @memberof RefundsPost503Response
     */
    errorCode?: RefundsPost503ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof RefundsPost503Response
     */
    message?: string;
}


/**
 * @export
 */
export const RefundsPost503ResponseErrorCodeEnum = {
    ChannelUnavailable: 'CHANNEL_UNAVAILABLE',
    OtpDeliveryError: 'OTP_DELIVERY_ERROR'
} as const;
export type RefundsPost503ResponseErrorCodeEnum = typeof RefundsPost503ResponseErrorCodeEnum[keyof typeof RefundsPost503ResponseErrorCodeEnum];


/**
 * Check if a given object implements the RefundsPost503Response interface.
 */
export function instanceOfRefundsPost503Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefundsPost503ResponseFromJSON(json: any): RefundsPost503Response {
    return RefundsPost503ResponseFromJSONTyped(json, false);
}

export function RefundsPost503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundsPost503Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function RefundsPost503ResponseToJSON(value?: RefundsPost503Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

