/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface ErrorV2ResponseErrorsInner
 */
export interface ErrorV2ResponseErrorsInner {
    /**
     * Precise location of the error
     * @type {string}
     * @memberof ErrorV2ResponseErrorsInner
     */
    path: string;
    /**
     * Specific description of the error
     * @type {string}
     * @memberof ErrorV2ResponseErrorsInner
     */
    message: string;
    /**
     * Link to doc url so user can troubleshoot error easily
     * @type {string}
     * @memberof ErrorV2ResponseErrorsInner
     */
    docUrl?: string;
}

/**
 * Check if a given object implements the ErrorV2ResponseErrorsInner interface.
 */
export function instanceOfErrorV2ResponseErrorsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ErrorV2ResponseErrorsInnerFromJSON(json: any): ErrorV2ResponseErrorsInner {
    return ErrorV2ResponseErrorsInnerFromJSONTyped(json, false);
}

export function ErrorV2ResponseErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorV2ResponseErrorsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': json['path'],
        'message': json['message'],
        'docUrl': !exists(json, 'doc_url') ? undefined : json['doc_url'],
    };
}

export function ErrorV2ResponseErrorsInnerToJSON(value?: ErrorV2ResponseErrorsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'message': value.message,
        'doc_url': value.docUrl,
    };
}

