/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardBillingDetailsAddress } from './CardBillingDetailsAddress';
import {
    CardBillingDetailsAddressFromJSON,
    CardBillingDetailsAddressFromJSONTyped,
    CardBillingDetailsAddressToJSON,
} from './CardBillingDetailsAddress';

/**
 * Card Billing Details
 * @export
 * @interface CardBillingDetails
 */
export interface CardBillingDetails {
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    addressLine1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    addressCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    addressCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    addressPostalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    addressState?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    givenNames?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    middleName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    mobileNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetails
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {CardBillingDetailsAddress}
     * @memberof CardBillingDetails
     */
    address?: CardBillingDetailsAddress | null;
}

/**
 * Check if a given object implements the CardBillingDetails interface.
 */
export function instanceOfCardBillingDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardBillingDetailsFromJSON(json: any): CardBillingDetails {
    return CardBillingDetailsFromJSONTyped(json, false);
}

export function CardBillingDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardBillingDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'addressLine1': !exists(json, 'address_line_1') ? undefined : json['address_line_1'],
        'addressLine2': !exists(json, 'address_line_2') ? undefined : json['address_line_2'],
        'addressCity': !exists(json, 'address_city') ? undefined : json['address_city'],
        'addressCountry': !exists(json, 'address_country') ? undefined : json['address_country'],
        'addressPostalCode': !exists(json, 'address_postal_code') ? undefined : json['address_postal_code'],
        'addressState': !exists(json, 'address_state') ? undefined : json['address_state'],
        'givenNames': !exists(json, 'given_names') ? undefined : json['given_names'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'mobileNumber': !exists(json, 'mobile_number') ? undefined : json['mobile_number'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'address': !exists(json, 'address') ? undefined : CardBillingDetailsAddressFromJSON(json['address']),
    };
}

export function CardBillingDetailsToJSON(value?: CardBillingDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'email': value.email,
        'phone': value.phone,
        'address_line_1': value.addressLine1,
        'address_line_2': value.addressLine2,
        'address_city': value.addressCity,
        'address_country': value.addressCountry,
        'address_postal_code': value.addressPostalCode,
        'address_state': value.addressState,
        'given_names': value.givenNames,
        'middle_name': value.middleName,
        'surname': value.surname,
        'mobile_number': value.mobileNumber,
        'phone_number': value.phoneNumber,
        'address': CardBillingDetailsAddressToJSON(value.address),
    };
}

