/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { PaymentMethodCountry } from './PaymentMethodCountry';
import {
    PaymentMethodCountryFromJSON,
    PaymentMethodCountryFromJSONTyped,
    PaymentMethodCountryToJSON,
} from './PaymentMethodCountry';

/**
 * Channel code with country
 * @export
 * @interface ChannelWithCountry
 */
export interface ChannelWithCountry {
    /**
     * 
     * @type {string}
     * @memberof ChannelWithCountry
     */
    channelCode?: string | null;
    /**
     * 
     * @type {PaymentMethodCountry}
     * @memberof ChannelWithCountry
     */
    country?: PaymentMethodCountry;
}

/**
 * Check if a given object implements the ChannelWithCountry interface.
 */
export function instanceOfChannelWithCountry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelWithCountryFromJSON(json: any): ChannelWithCountry {
    return ChannelWithCountryFromJSONTyped(json, false);
}

export function ChannelWithCountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelWithCountry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': !exists(json, 'channel_code') ? undefined : json['channel_code'],
        'country': !exists(json, 'country') ? undefined : PaymentMethodCountryFromJSON(json['country']),
    };
}

export function ChannelWithCountryToJSON(value?: ChannelWithCountry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': value.channelCode,
        'country': PaymentMethodCountryToJSON(value.country),
    };
}

