/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DirectBankTransferChannelCode } from './DirectBankTransferChannelCode';
import {
    DirectBankTransferChannelCodeFromJSON,
    DirectBankTransferChannelCodeFromJSONTyped,
    DirectBankTransferChannelCodeToJSON,
} from './DirectBankTransferChannelCode';
import type { DirectBankTransferChannelProperties } from './DirectBankTransferChannelProperties';
import {
    DirectBankTransferChannelPropertiesFromJSON,
    DirectBankTransferChannelPropertiesFromJSONTyped,
    DirectBankTransferChannelPropertiesToJSON,
} from './DirectBankTransferChannelProperties';

/**
 * Direct Bank Transfer Payment Method Details
 * @export
 * @interface InternalDirectBankTransfer
 */
export interface InternalDirectBankTransfer {
    /**
     * 
     * @type {DirectBankTransferChannelCode}
     * @memberof InternalDirectBankTransfer
     */
    channelCode: DirectBankTransferChannelCode;
    /**
     * 
     * @type {DirectBankTransferChannelProperties}
     * @memberof InternalDirectBankTransfer
     */
    channelProperties: DirectBankTransferChannelProperties;
    /**
     * 
     * @type {string}
     * @memberof InternalDirectBankTransfer
     */
    linkedTokenId?: string | null;
}

/**
 * Check if a given object implements the InternalDirectBankTransfer interface.
 */
export function instanceOfInternalDirectBankTransfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function InternalDirectBankTransferFromJSON(json: any): InternalDirectBankTransfer {
    return InternalDirectBankTransferFromJSONTyped(json, false);
}

export function InternalDirectBankTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalDirectBankTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': DirectBankTransferChannelCodeFromJSON(json['channel_code']),
        'channelProperties': DirectBankTransferChannelPropertiesFromJSON(json['channel_properties']),
        'linkedTokenId': !exists(json, 'linked_token_id') ? undefined : json['linked_token_id'],
    };
}

export function InternalDirectBankTransferToJSON(value?: InternalDirectBankTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': DirectBankTransferChannelCodeToJSON(value.channelCode),
        'channel_properties': DirectBankTransferChannelPropertiesToJSON(value.channelProperties),
        'linked_token_id': value.linkedTokenId,
    };
}

