/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface InternalQRCodeAllOf
 */
export interface InternalQRCodeAllOf {
    /**
     * 
     * @type {string}
     * @memberof InternalQRCodeAllOf
     */
    qrCodeId?: string;
}

/**
 * Check if a given object implements the InternalQRCodeAllOf interface.
 */
export function instanceOfInternalQRCodeAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InternalQRCodeAllOfFromJSON(json: any): InternalQRCodeAllOf {
    return InternalQRCodeAllOfFromJSONTyped(json, false);
}

export function InternalQRCodeAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalQRCodeAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'qrCodeId': !exists(json, 'qr_code_id') ? undefined : json['qr_code_id'],
    };
}

export function InternalQRCodeAllOfToJSON(value?: InternalQRCodeAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'qr_code_id': value.qrCodeId,
    };
}

