/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { BillingInformation } from './BillingInformation';
import {
    BillingInformationFromJSON,
    BillingInformationFromJSONTyped,
    BillingInformationToJSON,
} from './BillingInformation';
import type { InternalCard } from './InternalCard';
import {
    InternalCardFromJSON,
    InternalCardFromJSONTyped,
    InternalCardToJSON,
} from './InternalCard';
import type { InternalCrypto } from './InternalCrypto';
import {
    InternalCryptoFromJSON,
    InternalCryptoFromJSONTyped,
    InternalCryptoToJSON,
} from './InternalCrypto';
import type { InternalDirectBankTransfer } from './InternalDirectBankTransfer';
import {
    InternalDirectBankTransferFromJSON,
    InternalDirectBankTransferFromJSONTyped,
    InternalDirectBankTransferToJSON,
} from './InternalDirectBankTransfer';
import type { InternalDirectDebit } from './InternalDirectDebit';
import {
    InternalDirectDebitFromJSON,
    InternalDirectDebitFromJSONTyped,
    InternalDirectDebitToJSON,
} from './InternalDirectDebit';
import type { InternalEwallet } from './InternalEwallet';
import {
    InternalEwalletFromJSON,
    InternalEwalletFromJSONTyped,
    InternalEwalletToJSON,
} from './InternalEwallet';
import type { InternalOverTheCounter } from './InternalOverTheCounter';
import {
    InternalOverTheCounterFromJSON,
    InternalOverTheCounterFromJSONTyped,
    InternalOverTheCounterToJSON,
} from './InternalOverTheCounter';
import type { InternalQRCode } from './InternalQRCode';
import {
    InternalQRCodeFromJSON,
    InternalQRCodeFromJSONTyped,
    InternalQRCodeToJSON,
} from './InternalQRCode';
import type { InternalVirtualAccount } from './InternalVirtualAccount';
import {
    InternalVirtualAccountFromJSON,
    InternalVirtualAccountFromJSONTyped,
    InternalVirtualAccountToJSON,
} from './InternalVirtualAccount';
import type { PaymentMethodAction } from './PaymentMethodAction';
import {
    PaymentMethodActionFromJSON,
    PaymentMethodActionFromJSONTyped,
    PaymentMethodActionToJSON,
} from './PaymentMethodAction';
import type { PaymentMethodCountry } from './PaymentMethodCountry';
import {
    PaymentMethodCountryFromJSON,
    PaymentMethodCountryFromJSONTyped,
    PaymentMethodCountryToJSON,
} from './PaymentMethodCountry';
import type { PaymentMethodReusability } from './PaymentMethodReusability';
import {
    PaymentMethodReusabilityFromJSON,
    PaymentMethodReusabilityFromJSONTyped,
    PaymentMethodReusabilityToJSON,
} from './PaymentMethodReusability';
import type { PaymentMethodStatus } from './PaymentMethodStatus';
import {
    PaymentMethodStatusFromJSON,
    PaymentMethodStatusFromJSONTyped,
    PaymentMethodStatusToJSON,
} from './PaymentMethodStatus';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
} from './PaymentMethodType';

/**
 * 
 * @export
 * @interface InternalPaymentMethod
 */
export interface InternalPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    businessId?: string;
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof InternalPaymentMethod
     */
    type?: PaymentMethodType;
    /**
     * 
     * @type {PaymentMethodCountry}
     * @memberof InternalPaymentMethod
     */
    country?: PaymentMethodCountry;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    customerId?: string | null;
    /**
     * 
     * @type {object}
     * @memberof InternalPaymentMethod
     */
    customer?: object | null;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    referenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    description?: string | null;
    /**
     * 
     * @type {PaymentMethodStatus}
     * @memberof InternalPaymentMethod
     */
    status?: PaymentMethodStatus;
    /**
     * 
     * @type {PaymentMethodReusability}
     * @memberof InternalPaymentMethod
     */
    reusability?: PaymentMethodReusability;
    /**
     * 
     * @type {Array<PaymentMethodAction>}
     * @memberof InternalPaymentMethod
     */
    actions?: Array<PaymentMethodAction>;
    /**
     * 
     * @type {object}
     * @memberof InternalPaymentMethod
     */
    metadata?: object | null;
    /**
     * 
     * @type {BillingInformation}
     * @memberof InternalPaymentMethod
     */
    billingInformation?: BillingInformation | null;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    failureCode?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InternalPaymentMethod
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InternalPaymentMethod
     */
    updated?: Date;
    /**
     * 
     * @type {InternalEwallet}
     * @memberof InternalPaymentMethod
     */
    ewallet?: InternalEwallet | null;
    /**
     * 
     * @type {InternalCard}
     * @memberof InternalPaymentMethod
     */
    card?: InternalCard | null;
    /**
     * 
     * @type {InternalCrypto}
     * @memberof InternalPaymentMethod
     */
    cryptocurrency?: InternalCrypto | null;
    /**
     * 
     * @type {InternalDirectBankTransfer}
     * @memberof InternalPaymentMethod
     */
    directBankTransfer?: InternalDirectBankTransfer | null;
    /**
     * 
     * @type {InternalDirectDebit}
     * @memberof InternalPaymentMethod
     */
    directDebit?: InternalDirectDebit | null;
    /**
     * 
     * @type {InternalOverTheCounter}
     * @memberof InternalPaymentMethod
     */
    overTheCounter?: InternalOverTheCounter | null;
    /**
     * 
     * @type {InternalVirtualAccount}
     * @memberof InternalPaymentMethod
     */
    virtualAccount?: InternalVirtualAccount | null;
    /**
     * 
     * @type {InternalQRCode}
     * @memberof InternalPaymentMethod
     */
    qrCode?: InternalQRCode | null;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    xCallbackUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InternalPaymentMethod
     */
    clientType?: string | null;
    /**
     * 
     * @type {object}
     * @memberof InternalPaymentMethod
     */
    internalMetadata?: object | null;
}

/**
 * Check if a given object implements the InternalPaymentMethod interface.
 */
export function instanceOfInternalPaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function InternalPaymentMethodFromJSON(json: any): InternalPaymentMethod {
    return InternalPaymentMethodFromJSONTyped(json, false);
}

export function InternalPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalPaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': !exists(json, 'business_id') ? undefined : json['business_id'],
        'type': !exists(json, 'type') ? undefined : PaymentMethodTypeFromJSON(json['type']),
        'country': !exists(json, 'country') ? undefined : PaymentMethodCountryFromJSON(json['country']),
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'customer': !exists(json, 'customer') ? undefined : json['customer'],
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : PaymentMethodStatusFromJSON(json['status']),
        'reusability': !exists(json, 'reusability') ? undefined : PaymentMethodReusabilityFromJSON(json['reusability']),
        'actions': !exists(json, 'actions') ? undefined : ((json['actions'] as Array<any>).map(PaymentMethodActionFromJSON)),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'billingInformation': !exists(json, 'billing_information') ? undefined : BillingInformationFromJSON(json['billing_information']),
        'failureCode': !exists(json, 'failure_code') ? undefined : json['failure_code'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
        'ewallet': !exists(json, 'ewallet') ? undefined : InternalEwalletFromJSON(json['ewallet']),
        'card': !exists(json, 'card') ? undefined : InternalCardFromJSON(json['card']),
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : InternalCryptoFromJSON(json['cryptocurrency']),
        'directBankTransfer': !exists(json, 'direct_bank_transfer') ? undefined : InternalDirectBankTransferFromJSON(json['direct_bank_transfer']),
        'directDebit': !exists(json, 'direct_debit') ? undefined : InternalDirectDebitFromJSON(json['direct_debit']),
        'overTheCounter': !exists(json, 'over_the_counter') ? undefined : InternalOverTheCounterFromJSON(json['over_the_counter']),
        'virtualAccount': !exists(json, 'virtual_account') ? undefined : InternalVirtualAccountFromJSON(json['virtual_account']),
        'qrCode': !exists(json, 'qr_code') ? undefined : InternalQRCodeFromJSON(json['qr_code']),
        'xCallbackUrl': !exists(json, 'x-callback-url') ? undefined : json['x-callback-url'],
        'clientType': !exists(json, 'client_type') ? undefined : json['client_type'],
        'internalMetadata': !exists(json, 'internal_metadata') ? undefined : json['internal_metadata'],
    };
}

export function InternalPaymentMethodToJSON(value?: InternalPaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'business_id': value.businessId,
        'type': PaymentMethodTypeToJSON(value.type),
        'country': PaymentMethodCountryToJSON(value.country),
        'customer_id': value.customerId,
        'customer': value.customer,
        'reference_id': value.referenceId,
        'description': value.description,
        'status': PaymentMethodStatusToJSON(value.status),
        'reusability': PaymentMethodReusabilityToJSON(value.reusability),
        'actions': value.actions === undefined ? undefined : ((value.actions as Array<any>).map(PaymentMethodActionToJSON)),
        'metadata': value.metadata,
        'billing_information': BillingInformationToJSON(value.billingInformation),
        'failure_code': value.failureCode,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'updated': value.updated === undefined ? undefined : (value.updated.toISOString()),
        'ewallet': InternalEwalletToJSON(value.ewallet),
        'card': InternalCardToJSON(value.card),
        'cryptocurrency': InternalCryptoToJSON(value.cryptocurrency),
        'direct_bank_transfer': InternalDirectBankTransferToJSON(value.directBankTransfer),
        'direct_debit': InternalDirectDebitToJSON(value.directDebit),
        'over_the_counter': InternalOverTheCounterToJSON(value.overTheCounter),
        'virtual_account': InternalVirtualAccountToJSON(value.virtualAccount),
        'qr_code': InternalQRCodeToJSON(value.qrCode),
        'x-callback-url': value.xCallbackUrl,
        'client_type': value.clientType,
        'internal_metadata': value.internalMetadata,
    };
}

