/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface InternalDirectBankTransferAllOf
 */
export interface InternalDirectBankTransferAllOf {
    /**
     * 
     * @type {string}
     * @memberof InternalDirectBankTransferAllOf
     */
    linkedTokenId?: string | null;
}

/**
 * Check if a given object implements the InternalDirectBankTransferAllOf interface.
 */
export function instanceOfInternalDirectBankTransferAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InternalDirectBankTransferAllOfFromJSON(json: any): InternalDirectBankTransferAllOf {
    return InternalDirectBankTransferAllOfFromJSONTyped(json, false);
}

export function InternalDirectBankTransferAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalDirectBankTransferAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'linkedTokenId': !exists(json, 'linked_token_id') ? undefined : json['linked_token_id'],
    };
}

export function InternalDirectBankTransferAllOfToJSON(value?: InternalDirectBankTransferAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'linked_token_id': value.linkedTokenId,
    };
}

