/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface InternalEwalletAllOf
 */
export interface InternalEwalletAllOf {
    /**
     * 
     * @type {string}
     * @memberof InternalEwalletAllOf
     */
    linkedAccountTokenId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InternalEwalletAllOf
     */
    linkedAccountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InternalEwalletAllOf
     */
    accessToken?: string | null;
}

/**
 * Check if a given object implements the InternalEwalletAllOf interface.
 */
export function instanceOfInternalEwalletAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InternalEwalletAllOfFromJSON(json: any): InternalEwalletAllOf {
    return InternalEwalletAllOfFromJSONTyped(json, false);
}

export function InternalEwalletAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalEwalletAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'linkedAccountTokenId': !exists(json, 'linked_account_token_id') ? undefined : json['linked_account_token_id'],
        'linkedAccountId': !exists(json, 'linked_account_id') ? undefined : json['linked_account_id'],
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
    };
}

export function InternalEwalletAllOfToJSON(value?: InternalEwalletAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'linked_account_token_id': value.linkedAccountTokenId,
        'linked_account_id': value.linkedAccountId,
        'access_token': value.accessToken,
    };
}

