/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { QRCodeChannelCode } from './QRCodeChannelCode';
import {
    QRCodeChannelCodeFromJSON,
    QRCodeChannelCodeFromJSONTyped,
    QRCodeChannelCodeToJSON,
} from './QRCodeChannelCode';
import type { QRCodeChannelProperties } from './QRCodeChannelProperties';
import {
    QRCodeChannelPropertiesFromJSON,
    QRCodeChannelPropertiesFromJSONTyped,
    QRCodeChannelPropertiesToJSON,
} from './QRCodeChannelProperties';

/**
 * QR Code Payment Method Details
 * @export
 * @interface InternalQRCode
 */
export interface InternalQRCode {
    /**
     * 
     * @type {number}
     * @memberof InternalQRCode
     */
    amount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InternalQRCode
     */
    currency?: string;
    /**
     * 
     * @type {QRCodeChannelCode}
     * @memberof InternalQRCode
     */
    channelCode?: QRCodeChannelCode | null;
    /**
     * 
     * @type {QRCodeChannelProperties}
     * @memberof InternalQRCode
     */
    channelProperties?: QRCodeChannelProperties | null;
    /**
     * 
     * @type {string}
     * @memberof InternalQRCode
     */
    qrCodeId?: string;
}

/**
 * Check if a given object implements the InternalQRCode interface.
 */
export function instanceOfInternalQRCode(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InternalQRCodeFromJSON(json: any): InternalQRCode {
    return InternalQRCodeFromJSONTyped(json, false);
}

export function InternalQRCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalQRCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'channelCode': !exists(json, 'channel_code') ? undefined : QRCodeChannelCodeFromJSON(json['channel_code']),
        'channelProperties': !exists(json, 'channel_properties') ? undefined : QRCodeChannelPropertiesFromJSON(json['channel_properties']),
        'qrCodeId': !exists(json, 'qr_code_id') ? undefined : json['qr_code_id'],
    };
}

export function InternalQRCodeToJSON(value?: InternalQRCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
        'channel_code': QRCodeChannelCodeToJSON(value.channelCode),
        'channel_properties': QRCodeChannelPropertiesToJSON(value.channelProperties),
        'qr_code_id': value.qrCodeId,
    };
}

