/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { VirtualAccountAlternativeDisplay } from './VirtualAccountAlternativeDisplay';
import {
    VirtualAccountAlternativeDisplayFromJSON,
    VirtualAccountAlternativeDisplayFromJSONTyped,
    VirtualAccountAlternativeDisplayToJSON,
} from './VirtualAccountAlternativeDisplay';

/**
 * 
 * @export
 * @interface InternalVirtualAccountAllOf
 */
export interface InternalVirtualAccountAllOf {
    /**
     * 
     * @type {string}
     * @memberof InternalVirtualAccountAllOf
     */
    virtualAccountId?: string;
    /**
     * 
     * @type {Array<VirtualAccountAlternativeDisplay>}
     * @memberof InternalVirtualAccountAllOf
     */
    alternativeDisplays?: Array<VirtualAccountAlternativeDisplay>;
}

/**
 * Check if a given object implements the InternalVirtualAccountAllOf interface.
 */
export function instanceOfInternalVirtualAccountAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InternalVirtualAccountAllOfFromJSON(json: any): InternalVirtualAccountAllOf {
    return InternalVirtualAccountAllOfFromJSONTyped(json, false);
}

export function InternalVirtualAccountAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalVirtualAccountAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'virtualAccountId': !exists(json, 'virtual_account_id') ? undefined : json['virtual_account_id'],
        'alternativeDisplays': !exists(json, 'alternative_displays') ? undefined : ((json['alternative_displays'] as Array<any>).map(VirtualAccountAlternativeDisplayFromJSON)),
    };
}

export function InternalVirtualAccountAllOfToJSON(value?: InternalVirtualAccountAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'virtual_account_id': value.virtualAccountId,
        'alternative_displays': value.alternativeDisplays === undefined ? undefined : ((value.alternativeDisplays as Array<any>).map(VirtualAccountAlternativeDisplayToJSON)),
    };
}

