/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { VirtualAccountAlternativeDisplay } from './VirtualAccountAlternativeDisplay';
import {
    VirtualAccountAlternativeDisplayFromJSON,
    VirtualAccountAlternativeDisplayFromJSONTyped,
    VirtualAccountAlternativeDisplayToJSON,
} from './VirtualAccountAlternativeDisplay';
import type { VirtualAccountChannelCode } from './VirtualAccountChannelCode';
import {
    VirtualAccountChannelCodeFromJSON,
    VirtualAccountChannelCodeFromJSONTyped,
    VirtualAccountChannelCodeToJSON,
} from './VirtualAccountChannelCode';
import type { VirtualAccountChannelProperties } from './VirtualAccountChannelProperties';
import {
    VirtualAccountChannelPropertiesFromJSON,
    VirtualAccountChannelPropertiesFromJSONTyped,
    VirtualAccountChannelPropertiesToJSON,
} from './VirtualAccountChannelProperties';

/**
 * Virtual Account Payment Method Details
 * @export
 * @interface InternalVirtualAccount
 */
export interface InternalVirtualAccount {
    /**
     * 
     * @type {number}
     * @memberof InternalVirtualAccount
     */
    amount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InternalVirtualAccount
     */
    minAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InternalVirtualAccount
     */
    maxAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InternalVirtualAccount
     */
    currency?: string;
    /**
     * 
     * @type {VirtualAccountChannelCode}
     * @memberof InternalVirtualAccount
     */
    channelCode: VirtualAccountChannelCode;
    /**
     * 
     * @type {VirtualAccountChannelProperties}
     * @memberof InternalVirtualAccount
     */
    channelProperties: VirtualAccountChannelProperties;
    /**
     * Alternative display requested for the virtual account
     * @type {Array<string>}
     * @memberof InternalVirtualAccount
     */
    alternativeDisplayTypes?: Array<InternalVirtualAccountAlternativeDisplayTypesEnum>;
    /**
     * 
     * @type {string}
     * @memberof InternalVirtualAccount
     */
    virtualAccountId?: string;
    /**
     * 
     * @type {Array<VirtualAccountAlternativeDisplay>}
     * @memberof InternalVirtualAccount
     */
    alternativeDisplays?: Array<VirtualAccountAlternativeDisplay>;
}


/**
 * @export
 */
export const InternalVirtualAccountAlternativeDisplayTypesEnum = {
    QrString: 'QR_STRING'
} as const;
export type InternalVirtualAccountAlternativeDisplayTypesEnum = typeof InternalVirtualAccountAlternativeDisplayTypesEnum[keyof typeof InternalVirtualAccountAlternativeDisplayTypesEnum];


/**
 * Check if a given object implements the InternalVirtualAccount interface.
 */
export function instanceOfInternalVirtualAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function InternalVirtualAccountFromJSON(json: any): InternalVirtualAccount {
    return InternalVirtualAccountFromJSONTyped(json, false);
}

export function InternalVirtualAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalVirtualAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'minAmount': !exists(json, 'min_amount') ? undefined : json['min_amount'],
        'maxAmount': !exists(json, 'max_amount') ? undefined : json['max_amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'channelCode': VirtualAccountChannelCodeFromJSON(json['channel_code']),
        'channelProperties': VirtualAccountChannelPropertiesFromJSON(json['channel_properties']),
        'alternativeDisplayTypes': !exists(json, 'alternative_display_types') ? undefined : json['alternative_display_types'],
        'virtualAccountId': !exists(json, 'virtual_account_id') ? undefined : json['virtual_account_id'],
        'alternativeDisplays': !exists(json, 'alternative_displays') ? undefined : ((json['alternative_displays'] as Array<any>).map(VirtualAccountAlternativeDisplayFromJSON)),
    };
}

export function InternalVirtualAccountToJSON(value?: InternalVirtualAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'min_amount': value.minAmount,
        'max_amount': value.maxAmount,
        'currency': value.currency,
        'channel_code': VirtualAccountChannelCodeToJSON(value.channelCode),
        'channel_properties': VirtualAccountChannelPropertiesToJSON(value.channelProperties),
        'alternative_display_types': value.alternativeDisplayTypes,
        'virtual_account_id': value.virtualAccountId,
        'alternative_displays': value.alternativeDisplays === undefined ? undefined : ((value.alternativeDisplays as Array<any>).map(VirtualAccountAlternativeDisplayToJSON)),
    };
}

