/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardChannelProperties } from './CardChannelProperties';
import {
    CardChannelPropertiesFromJSON,
    CardChannelPropertiesFromJSONTyped,
    CardChannelPropertiesToJSON,
} from './CardChannelProperties';
import type { CardToken } from './CardToken';
import {
    CardTokenFromJSON,
    CardTokenFromJSONTyped,
    CardTokenToJSON,
} from './CardToken';
import type { CardVerificationResults } from './CardVerificationResults';
import {
    CardVerificationResultsFromJSON,
    CardVerificationResultsFromJSONTyped,
    CardVerificationResultsToJSON,
} from './CardVerificationResults';
import type { TokenizedCardInformation } from './TokenizedCardInformation';
import {
    TokenizedCardInformationFromJSON,
    TokenizedCardInformationFromJSONTyped,
    TokenizedCardInformationToJSON,
} from './TokenizedCardInformation';

/**
 * 
 * @export
 * @interface MutableCard
 */
export interface MutableCard {
    /**
     * 
     * @type {string}
     * @memberof MutableCard
     */
    currency: string;
    /**
     * 
     * @type {CardChannelProperties}
     * @memberof MutableCard
     */
    channelProperties?: CardChannelProperties | null;
    /**
     * 
     * @type {TokenizedCardInformation}
     * @memberof MutableCard
     */
    cardInformation?: TokenizedCardInformation;
    /**
     * 
     * @type {CardVerificationResults}
     * @memberof MutableCard
     */
    cardVerificationResults?: CardVerificationResults | null;
    /**
     * 
     * @type {CardToken}
     * @memberof MutableCard
     */
    token?: CardToken;
}

/**
 * Check if a given object implements the MutableCard interface.
 */
export function instanceOfMutableCard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function MutableCardFromJSON(json: any): MutableCard {
    return MutableCardFromJSONTyped(json, false);
}

export function MutableCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutableCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'channelProperties': !exists(json, 'channel_properties') ? undefined : CardChannelPropertiesFromJSON(json['channel_properties']),
        'cardInformation': !exists(json, 'card_information') ? undefined : TokenizedCardInformationFromJSON(json['card_information']),
        'cardVerificationResults': !exists(json, 'card_verification_results') ? undefined : CardVerificationResultsFromJSON(json['card_verification_results']),
        'token': !exists(json, 'token') ? undefined : CardTokenFromJSON(json['token']),
    };
}

export function MutableCardToJSON(value?: MutableCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': value.currency,
        'channel_properties': CardChannelPropertiesToJSON(value.channelProperties),
        'card_information': TokenizedCardInformationToJSON(value.cardInformation),
        'card_verification_results': CardVerificationResultsToJSON(value.cardVerificationResults),
        'token': CardTokenToJSON(value.token),
    };
}

