/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Over The Counter Channel Properties Patchables
 * @export
 * @interface OverTheCounterChannelPropertiesPatch
 */
export interface OverTheCounterChannelPropertiesPatch {
    /**
     * Name of customer.
     * @type {string}
     * @memberof OverTheCounterChannelPropertiesPatch
     */
    customerName?: string;
    /**
     * The time when the payment code will be expired. The minimum is 2 hours and the maximum is 9 days for 7ELEVEN. Default expired date will be 2 days from payment code generated.
     * @type {Date}
     * @memberof OverTheCounterChannelPropertiesPatch
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the OverTheCounterChannelPropertiesPatch interface.
 */
export function instanceOfOverTheCounterChannelPropertiesPatch(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OverTheCounterChannelPropertiesPatchFromJSON(json: any): OverTheCounterChannelPropertiesPatch {
    return OverTheCounterChannelPropertiesPatchFromJSONTyped(json, false);
}

export function OverTheCounterChannelPropertiesPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverTheCounterChannelPropertiesPatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerName': !exists(json, 'customer_name') ? undefined : json['customer_name'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : (new Date(json['expires_at'])),
    };
}

export function OverTheCounterChannelPropertiesPatchToJSON(value?: OverTheCounterChannelPropertiesPatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_name': value.customerName,
        'expires_at': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
    };
}

