/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CryptoChannelCode } from './CryptoChannelCode';
import {
    CryptoChannelCodeFromJSON,
    CryptoChannelCodeFromJSONTyped,
    CryptoChannelCodeToJSON,
} from './CryptoChannelCode';
import type { CryptoWallet } from './CryptoWallet';
import {
    CryptoWalletFromJSON,
    CryptoWalletFromJSONTyped,
    CryptoWalletToJSON,
} from './CryptoWallet';

/**
 * 
 * @export
 * @interface PatchCrypto
 */
export interface PatchCrypto {
    /**
     * 
     * @type {CryptoChannelCode}
     * @memberof PatchCrypto
     */
    channelCode?: CryptoChannelCode | null;
    /**
     * 
     * @type {CryptoWallet}
     * @memberof PatchCrypto
     */
    wallet?: CryptoWallet | null;
}

/**
 * Check if a given object implements the PatchCrypto interface.
 */
export function instanceOfPatchCrypto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchCryptoFromJSON(json: any): PatchCrypto {
    return PatchCryptoFromJSONTyped(json, false);
}

export function PatchCryptoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchCrypto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': !exists(json, 'channel_code') ? undefined : CryptoChannelCodeFromJSON(json['channel_code']),
        'wallet': !exists(json, 'wallet') ? undefined : CryptoWalletFromJSON(json['wallet']),
    };
}

export function PatchCryptoToJSON(value?: PatchCrypto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': CryptoChannelCodeToJSON(value.channelCode),
        'wallet': CryptoWalletToJSON(value.wallet),
    };
}

