/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { OverTheCounterChannelPropertiesPatch } from './OverTheCounterChannelPropertiesPatch';
import {
    OverTheCounterChannelPropertiesPatchFromJSON,
    OverTheCounterChannelPropertiesPatchFromJSONTyped,
    OverTheCounterChannelPropertiesPatchToJSON,
} from './OverTheCounterChannelPropertiesPatch';

/**
 * 
 * @export
 * @interface PatchOverTheCounter
 */
export interface PatchOverTheCounter {
    /**
     * 
     * @type {number}
     * @memberof PatchOverTheCounter
     */
    amount?: number | null;
    /**
     * 
     * @type {OverTheCounterChannelPropertiesPatch}
     * @memberof PatchOverTheCounter
     */
    channelProperties?: OverTheCounterChannelPropertiesPatch;
}

/**
 * Check if a given object implements the PatchOverTheCounter interface.
 */
export function instanceOfPatchOverTheCounter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchOverTheCounterFromJSON(json: any): PatchOverTheCounter {
    return PatchOverTheCounterFromJSONTyped(json, false);
}

export function PatchOverTheCounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchOverTheCounter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'channelProperties': !exists(json, 'channel_properties') ? undefined : OverTheCounterChannelPropertiesPatchFromJSON(json['channel_properties']),
    };
}

export function PatchOverTheCounterToJSON(value?: PatchOverTheCounter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'channel_properties': OverTheCounterChannelPropertiesPatchToJSON(value.channelProperties),
    };
}

