/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicPostSimulatePaymentChannelHealth
 */
export interface PublicPostSimulatePaymentChannelHealth {
    /**
     * 
     * @type {string}
     * @memberof PublicPostSimulatePaymentChannelHealth
     */
    channelCode: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPostSimulatePaymentChannelHealth
     */
    status: PublicPostSimulatePaymentChannelHealthStatusEnum;
}


/**
 * @export
 */
export const PublicPostSimulatePaymentChannelHealthStatusEnum = {
    Online: 'ONLINE',
    UnplannedDowntime: 'UNPLANNED_DOWNTIME',
    ScheduledMaintenance: 'SCHEDULED_MAINTENANCE',
    DegradedServices: 'DEGRADED_SERVICES',
    PartnerUnplannedDowntime: 'PARTNER_UNPLANNED_DOWNTIME',
    PartnerScheduledMaintenance: 'PARTNER_SCHEDULED_MAINTENANCE',
    PartnerDegradedServices: 'PARTNER_DEGRADED_SERVICES'
} as const;
export type PublicPostSimulatePaymentChannelHealthStatusEnum = typeof PublicPostSimulatePaymentChannelHealthStatusEnum[keyof typeof PublicPostSimulatePaymentChannelHealthStatusEnum];


/**
 * Check if a given object implements the PublicPostSimulatePaymentChannelHealth interface.
 */
export function instanceOfPublicPostSimulatePaymentChannelHealth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function PublicPostSimulatePaymentChannelHealthFromJSON(json: any): PublicPostSimulatePaymentChannelHealth {
    return PublicPostSimulatePaymentChannelHealthFromJSONTyped(json, false);
}

export function PublicPostSimulatePaymentChannelHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPostSimulatePaymentChannelHealth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': json['channel_code'],
        'status': json['status'],
    };
}

export function PublicPostSimulatePaymentChannelHealthToJSON(value?: PublicPostSimulatePaymentChannelHealth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': value.channelCode,
        'status': value.status,
    };
}

