/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicPaymentChannelListLinksInner
 */
export interface PublicPaymentChannelListLinksInner {
    /**
     * Target URI that should contain a target to Internationalized Resource Identifiers (IRI)
     * @type {string}
     * @memberof PublicPaymentChannelListLinksInner
     */
    href?: string;
    /**
     * The link relation type described how the current context (source) is related to target resource
     * @type {string}
     * @memberof PublicPaymentChannelListLinksInner
     */
    rel?: PublicPaymentChannelListLinksInnerRelEnum;
    /**
     * The HTTP method to be used to call `href`
     * @type {string}
     * @memberof PublicPaymentChannelListLinksInner
     */
    method?: string;
}


/**
 * @export
 */
export const PublicPaymentChannelListLinksInnerRelEnum = {
    First: 'first',
    Last: 'last',
    Next: 'next',
    Prev: 'prev'
} as const;
export type PublicPaymentChannelListLinksInnerRelEnum = typeof PublicPaymentChannelListLinksInnerRelEnum[keyof typeof PublicPaymentChannelListLinksInnerRelEnum];


/**
 * Check if a given object implements the PublicPaymentChannelListLinksInner interface.
 */
export function instanceOfPublicPaymentChannelListLinksInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicPaymentChannelListLinksInnerFromJSON(json: any): PublicPaymentChannelListLinksInner {
    return PublicPaymentChannelListLinksInnerFromJSONTyped(json, false);
}

export function PublicPaymentChannelListLinksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPaymentChannelListLinksInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'rel': !exists(json, 'rel') ? undefined : json['rel'],
        'method': !exists(json, 'method') ? undefined : json['method'],
    };
}

export function PublicPaymentChannelListLinksInnerToJSON(value?: PublicPaymentChannelListLinksInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'rel': value.rel,
        'method': value.method,
    };
}

