/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicExpirePaymentMethod
 */
export interface PublicExpirePaymentMethod {
    /**
     * URL where the end customer is redirected if the unlinking authorization is successful.
     * @type {string}
     * @memberof PublicExpirePaymentMethod
     */
    successReturnUrl?: string | null;
    /**
     * URL where the end customer is redirected if the unlinking authorization is failed.
     * @type {string}
     * @memberof PublicExpirePaymentMethod
     */
    failureReturnUrl?: string | null;
}

/**
 * Check if a given object implements the PublicExpirePaymentMethod interface.
 */
export function instanceOfPublicExpirePaymentMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicExpirePaymentMethodFromJSON(json: any): PublicExpirePaymentMethod {
    return PublicExpirePaymentMethodFromJSONTyped(json, false);
}

export function PublicExpirePaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicExpirePaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'successReturnUrl': !exists(json, 'success_return_url') ? undefined : json['success_return_url'],
        'failureReturnUrl': !exists(json, 'failure_return_url') ? undefined : json['failure_return_url'],
    };
}

export function PublicExpirePaymentMethodToJSON(value?: PublicExpirePaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success_return_url': value.successReturnUrl,
        'failure_return_url': value.failureReturnUrl,
    };
}

