/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { PublicPaymentChannelDowntimeOnlineData } from './PublicPaymentChannelDowntimeOnlineData';
import {
    PublicPaymentChannelDowntimeOnlineDataFromJSON,
    PublicPaymentChannelDowntimeOnlineDataFromJSONTyped,
    PublicPaymentChannelDowntimeOnlineDataToJSON,
} from './PublicPaymentChannelDowntimeOnlineData';

/**
 * 
 * @export
 * @interface PublicPaymentChannelDowntimeOnlineAllOf
 */
export interface PublicPaymentChannelDowntimeOnlineAllOf {
    /**
     * Payment channel health event
     * @type {string}
     * @memberof PublicPaymentChannelDowntimeOnlineAllOf
     */
    event?: string;
    /**
     * Business ID registered to payment channel downtime or online callback URL
     * @type {string}
     * @memberof PublicPaymentChannelDowntimeOnlineAllOf
     */
    businessId?: string;
    /**
     * Date time the event is triggered
     * @type {string}
     * @memberof PublicPaymentChannelDowntimeOnlineAllOf
     */
    created?: string;
    /**
     * 
     * @type {PublicPaymentChannelDowntimeOnlineData}
     * @memberof PublicPaymentChannelDowntimeOnlineAllOf
     */
    data?: PublicPaymentChannelDowntimeOnlineData;
}

/**
 * Check if a given object implements the PublicPaymentChannelDowntimeOnlineAllOf interface.
 */
export function instanceOfPublicPaymentChannelDowntimeOnlineAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicPaymentChannelDowntimeOnlineAllOfFromJSON(json: any): PublicPaymentChannelDowntimeOnlineAllOf {
    return PublicPaymentChannelDowntimeOnlineAllOfFromJSONTyped(json, false);
}

export function PublicPaymentChannelDowntimeOnlineAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPaymentChannelDowntimeOnlineAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'event': !exists(json, 'event') ? undefined : json['event'],
        'businessId': !exists(json, 'business_id') ? undefined : json['business_id'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'data': !exists(json, 'data') ? undefined : PublicPaymentChannelDowntimeOnlineDataFromJSON(json['data']),
    };
}

export function PublicPaymentChannelDowntimeOnlineAllOfToJSON(value?: PublicPaymentChannelDowntimeOnlineAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event': value.event,
        'business_id': value.businessId,
        'created': value.created,
        'data': PublicPaymentChannelDowntimeOnlineDataToJSON(value.data),
    };
}

