/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { BillingInformation } from './BillingInformation';
import {
    BillingInformationFromJSON,
    BillingInformationFromJSONTyped,
    BillingInformationToJSON,
} from './BillingInformation';
import type { MutableCrypto } from './MutableCrypto';
import {
    MutableCryptoFromJSON,
    MutableCryptoFromJSONTyped,
    MutableCryptoToJSON,
} from './MutableCrypto';
import type { MutableDirectBankTransfer } from './MutableDirectBankTransfer';
import {
    MutableDirectBankTransferFromJSON,
    MutableDirectBankTransferFromJSONTyped,
    MutableDirectBankTransferToJSON,
} from './MutableDirectBankTransfer';
import type { MutableDirectDebit } from './MutableDirectDebit';
import {
    MutableDirectDebitFromJSON,
    MutableDirectDebitFromJSONTyped,
    MutableDirectDebitToJSON,
} from './MutableDirectDebit';
import type { MutableEwallet } from './MutableEwallet';
import {
    MutableEwalletFromJSON,
    MutableEwalletFromJSONTyped,
    MutableEwalletToJSON,
} from './MutableEwallet';
import type { MutableOverTheCounter } from './MutableOverTheCounter';
import {
    MutableOverTheCounterFromJSON,
    MutableOverTheCounterFromJSONTyped,
    MutableOverTheCounterToJSON,
} from './MutableOverTheCounter';
import type { MutableQRCode } from './MutableQRCode';
import {
    MutableQRCodeFromJSON,
    MutableQRCodeFromJSONTyped,
    MutableQRCodeToJSON,
} from './MutableQRCode';
import type { MutableVirtualAccount } from './MutableVirtualAccount';
import {
    MutableVirtualAccountFromJSON,
    MutableVirtualAccountFromJSONTyped,
    MutableVirtualAccountToJSON,
} from './MutableVirtualAccount';
import type { OptionalPaymentMethodCountry } from './OptionalPaymentMethodCountry';
import {
    OptionalPaymentMethodCountryFromJSON,
    OptionalPaymentMethodCountryFromJSONTyped,
    OptionalPaymentMethodCountryToJSON,
} from './OptionalPaymentMethodCountry';
import type { PaymentMethodReusability } from './PaymentMethodReusability';
import {
    PaymentMethodReusabilityFromJSON,
    PaymentMethodReusabilityFromJSONTyped,
    PaymentMethodReusabilityToJSON,
} from './PaymentMethodReusability';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
} from './PaymentMethodType';

/**
 * 
 * @export
 * @interface PublicCreatePaymentMethod
 */
export interface PublicCreatePaymentMethod {
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof PublicCreatePaymentMethod
     */
    type: PaymentMethodType;
    /**
     * 
     * @type {OptionalPaymentMethodCountry}
     * @memberof PublicCreatePaymentMethod
     */
    country?: OptionalPaymentMethodCountry | null;
    /**
     * 
     * @type {PaymentMethodReusability}
     * @memberof PublicCreatePaymentMethod
     */
    reusability: PaymentMethodReusability;
    /**
     * 
     * @type {string}
     * @memberof PublicCreatePaymentMethod
     */
    customerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicCreatePaymentMethod
     */
    referenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCreatePaymentMethod
     */
    description?: string | null;
    /**
     * 
     * @type {MutableCrypto}
     * @memberof PublicCreatePaymentMethod
     */
    cryptocurrency?: MutableCrypto;
    /**
     * 
     * @type {MutableDirectBankTransfer}
     * @memberof PublicCreatePaymentMethod
     */
    directBankTransfer?: MutableDirectBankTransfer;
    /**
     * 
     * @type {MutableDirectDebit}
     * @memberof PublicCreatePaymentMethod
     */
    directDebit?: MutableDirectDebit;
    /**
     * 
     * @type {MutableEwallet}
     * @memberof PublicCreatePaymentMethod
     */
    ewallet?: MutableEwallet;
    /**
     * 
     * @type {MutableOverTheCounter}
     * @memberof PublicCreatePaymentMethod
     */
    overTheCounter?: MutableOverTheCounter;
    /**
     * 
     * @type {MutableVirtualAccount}
     * @memberof PublicCreatePaymentMethod
     */
    virtualAccount?: MutableVirtualAccount;
    /**
     * 
     * @type {MutableQRCode}
     * @memberof PublicCreatePaymentMethod
     */
    qrCode?: MutableQRCode;
    /**
     * 
     * @type {object}
     * @memberof PublicCreatePaymentMethod
     */
    metadata?: object | null;
    /**
     * 
     * @type {BillingInformation}
     * @memberof PublicCreatePaymentMethod
     */
    billingInformation?: BillingInformation | null;
}

/**
 * Check if a given object implements the PublicCreatePaymentMethod interface.
 */
export function instanceOfPublicCreatePaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "reusability" in value;

    return isInstance;
}

export function PublicCreatePaymentMethodFromJSON(json: any): PublicCreatePaymentMethod {
    return PublicCreatePaymentMethodFromJSONTyped(json, false);
}

export function PublicCreatePaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCreatePaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': PaymentMethodTypeFromJSON(json['type']),
        'country': !exists(json, 'country') ? undefined : OptionalPaymentMethodCountryFromJSON(json['country']),
        'reusability': PaymentMethodReusabilityFromJSON(json['reusability']),
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : MutableCryptoFromJSON(json['cryptocurrency']),
        'directBankTransfer': !exists(json, 'direct_bank_transfer') ? undefined : MutableDirectBankTransferFromJSON(json['direct_bank_transfer']),
        'directDebit': !exists(json, 'direct_debit') ? undefined : MutableDirectDebitFromJSON(json['direct_debit']),
        'ewallet': !exists(json, 'ewallet') ? undefined : MutableEwalletFromJSON(json['ewallet']),
        'overTheCounter': !exists(json, 'over_the_counter') ? undefined : MutableOverTheCounterFromJSON(json['over_the_counter']),
        'virtualAccount': !exists(json, 'virtual_account') ? undefined : MutableVirtualAccountFromJSON(json['virtual_account']),
        'qrCode': !exists(json, 'qr_code') ? undefined : MutableQRCodeFromJSON(json['qr_code']),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'billingInformation': !exists(json, 'billing_information') ? undefined : BillingInformationFromJSON(json['billing_information']),
    };
}

export function PublicCreatePaymentMethodToJSON(value?: PublicCreatePaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': PaymentMethodTypeToJSON(value.type),
        'country': OptionalPaymentMethodCountryToJSON(value.country),
        'reusability': PaymentMethodReusabilityToJSON(value.reusability),
        'customer_id': value.customerId,
        'reference_id': value.referenceId,
        'description': value.description,
        'cryptocurrency': MutableCryptoToJSON(value.cryptocurrency),
        'direct_bank_transfer': MutableDirectBankTransferToJSON(value.directBankTransfer),
        'direct_debit': MutableDirectDebitToJSON(value.directDebit),
        'ewallet': MutableEwalletToJSON(value.ewallet),
        'over_the_counter': MutableOverTheCounterToJSON(value.overTheCounter),
        'virtual_account': MutableVirtualAccountToJSON(value.virtualAccount),
        'qr_code': MutableQRCodeToJSON(value.qrCode),
        'metadata': value.metadata,
        'billing_information': BillingInformationToJSON(value.billingInformation),
    };
}

