/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DirectBankTransferChannelCode } from './DirectBankTransferChannelCode';
import {
    DirectBankTransferChannelCodeFromJSON,
    DirectBankTransferChannelCodeFromJSONTyped,
    DirectBankTransferChannelCodeToJSON,
} from './DirectBankTransferChannelCode';
import type { DirectBankTransferChannelProperties } from './DirectBankTransferChannelProperties';
import {
    DirectBankTransferChannelPropertiesFromJSON,
    DirectBankTransferChannelPropertiesFromJSONTyped,
    DirectBankTransferChannelPropertiesToJSON,
} from './DirectBankTransferChannelProperties';

/**
 * Direct Bank Transfer Payment Method Details
 * @export
 * @interface PublicDirectBankTransfer
 */
export interface PublicDirectBankTransfer {
    /**
     * 
     * @type {DirectBankTransferChannelCode}
     * @memberof PublicDirectBankTransfer
     */
    channelCode: DirectBankTransferChannelCode;
    /**
     * 
     * @type {DirectBankTransferChannelProperties}
     * @memberof PublicDirectBankTransfer
     */
    channelProperties: DirectBankTransferChannelProperties;
}

/**
 * Check if a given object implements the PublicDirectBankTransfer interface.
 */
export function instanceOfPublicDirectBankTransfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function PublicDirectBankTransferFromJSON(json: any): PublicDirectBankTransfer {
    return PublicDirectBankTransferFromJSONTyped(json, false);
}

export function PublicDirectBankTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicDirectBankTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': DirectBankTransferChannelCodeFromJSON(json['channel_code']),
        'channelProperties': DirectBankTransferChannelPropertiesFromJSON(json['channel_properties']),
    };
}

export function PublicDirectBankTransferToJSON(value?: PublicDirectBankTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': DirectBankTransferChannelCodeToJSON(value.channelCode),
        'channel_properties': DirectBankTransferChannelPropertiesToJSON(value.channelProperties),
    };
}

