/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardChannelProperties } from './CardChannelProperties';
import {
    CardChannelPropertiesFromJSON,
    CardChannelPropertiesFromJSONTyped,
    CardChannelPropertiesToJSON,
} from './CardChannelProperties';
import type { PublicSDKCardCardInformation } from './PublicSDKCardCardInformation';
import {
    PublicSDKCardCardInformationFromJSON,
    PublicSDKCardCardInformationFromJSONTyped,
    PublicSDKCardCardInformationToJSON,
} from './PublicSDKCardCardInformation';

/**
 * 
 * @export
 * @interface PublicSDKCard
 */
export interface PublicSDKCard {
    /**
     * 
     * @type {string}
     * @memberof PublicSDKCard
     */
    currency: string;
    /**
     * 
     * @type {CardChannelProperties}
     * @memberof PublicSDKCard
     */
    channelProperties?: CardChannelProperties | null;
    /**
     * 
     * @type {PublicSDKCardCardInformation}
     * @memberof PublicSDKCard
     */
    cardInformation?: PublicSDKCardCardInformation;
}

/**
 * Check if a given object implements the PublicSDKCard interface.
 */
export function instanceOfPublicSDKCard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function PublicSDKCardFromJSON(json: any): PublicSDKCard {
    return PublicSDKCardFromJSONTyped(json, false);
}

export function PublicSDKCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSDKCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'channelProperties': !exists(json, 'channel_properties') ? undefined : CardChannelPropertiesFromJSON(json['channel_properties']),
        'cardInformation': !exists(json, 'card_information') ? undefined : PublicSDKCardCardInformationFromJSON(json['card_information']),
    };
}

export function PublicSDKCardToJSON(value?: PublicSDKCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': value.currency,
        'channel_properties': CardChannelPropertiesToJSON(value.channelProperties),
        'card_information': PublicSDKCardCardInformationToJSON(value.cardInformation),
    };
}

