/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DirectDebitBankAccount } from './DirectDebitBankAccount';
import {
    DirectDebitBankAccountFromJSON,
    DirectDebitBankAccountFromJSONTyped,
    DirectDebitBankAccountToJSON,
} from './DirectDebitBankAccount';
import type { DirectDebitChannelCode } from './DirectDebitChannelCode';
import {
    DirectDebitChannelCodeFromJSON,
    DirectDebitChannelCodeFromJSONTyped,
    DirectDebitChannelCodeToJSON,
} from './DirectDebitChannelCode';
import type { DirectDebitChannelProperties } from './DirectDebitChannelProperties';
import {
    DirectDebitChannelPropertiesFromJSON,
    DirectDebitChannelPropertiesFromJSONTyped,
    DirectDebitChannelPropertiesToJSON,
} from './DirectDebitChannelProperties';
import type { DirectDebitDebitCard } from './DirectDebitDebitCard';
import {
    DirectDebitDebitCardFromJSON,
    DirectDebitDebitCardFromJSONTyped,
    DirectDebitDebitCardToJSON,
} from './DirectDebitDebitCard';
import type { DirectDebitType } from './DirectDebitType';
import {
    DirectDebitTypeFromJSON,
    DirectDebitTypeFromJSONTyped,
    DirectDebitTypeToJSON,
} from './DirectDebitType';

/**
 * Direct Debit Payment Method Details
 * @export
 * @interface PublicDirectDebit
 */
export interface PublicDirectDebit {
    /**
     * 
     * @type {DirectDebitChannelCode}
     * @memberof PublicDirectDebit
     */
    channelCode: DirectDebitChannelCode;
    /**
     * 
     * @type {DirectDebitChannelProperties}
     * @memberof PublicDirectDebit
     */
    channelProperties: DirectDebitChannelProperties | null;
    /**
     * 
     * @type {DirectDebitType}
     * @memberof PublicDirectDebit
     */
    type: DirectDebitType;
    /**
     * 
     * @type {DirectDebitBankAccount}
     * @memberof PublicDirectDebit
     */
    bankAccount?: DirectDebitBankAccount | null;
    /**
     * 
     * @type {DirectDebitDebitCard}
     * @memberof PublicDirectDebit
     */
    debitCard?: DirectDebitDebitCard | null;
}

/**
 * Check if a given object implements the PublicDirectDebit interface.
 */
export function instanceOfPublicDirectDebit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PublicDirectDebitFromJSON(json: any): PublicDirectDebit {
    return PublicDirectDebitFromJSONTyped(json, false);
}

export function PublicDirectDebitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicDirectDebit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': DirectDebitChannelCodeFromJSON(json['channel_code']),
        'channelProperties': DirectDebitChannelPropertiesFromJSON(json['channel_properties']),
        'type': DirectDebitTypeFromJSON(json['type']),
        'bankAccount': !exists(json, 'bank_account') ? undefined : DirectDebitBankAccountFromJSON(json['bank_account']),
        'debitCard': !exists(json, 'debit_card') ? undefined : DirectDebitDebitCardFromJSON(json['debit_card']),
    };
}

export function PublicDirectDebitToJSON(value?: PublicDirectDebit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': DirectDebitChannelCodeToJSON(value.channelCode),
        'channel_properties': DirectDebitChannelPropertiesToJSON(value.channelProperties),
        'type': DirectDebitTypeToJSON(value.type),
        'bank_account': DirectDebitBankAccountToJSON(value.bankAccount),
        'debit_card': DirectDebitDebitCardToJSON(value.debitCard),
    };
}

