/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Card Billing Details Address
 * @export
 * @interface CardBillingDetailsAddress
 */
export interface CardBillingDetailsAddress {
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    streetLine1?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    streetLine2?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    provinceState?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    province?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof CardBillingDetailsAddress
     */
    description?: string;
}

/**
 * Check if a given object implements the CardBillingDetailsAddress interface.
 */
export function instanceOfCardBillingDetailsAddress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardBillingDetailsAddressFromJSON(json: any): CardBillingDetailsAddress {
    return CardBillingDetailsAddressFromJSONTyped(json, false);
}

export function CardBillingDetailsAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardBillingDetailsAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': !exists(json, 'country') ? undefined : json['country'],
        'streetLine1': !exists(json, 'street_line1') ? undefined : json['street_line1'],
        'streetLine2': !exists(json, 'street_line2') ? undefined : json['street_line2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'provinceState': !exists(json, 'province_state') ? undefined : json['province_state'],
        'province': !exists(json, 'province') ? undefined : json['province'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'postalCode': !exists(json, 'postal_code') ? undefined : json['postal_code'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CardBillingDetailsAddressToJSON(value?: CardBillingDetailsAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'street_line1': value.streetLine1,
        'street_line2': value.streetLine2,
        'city': value.city,
        'province_state': value.provinceState,
        'province': value.province,
        'state': value.state,
        'postal_code': value.postalCode,
        'category': value.category,
        'description': value.description,
    };
}

