/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardBillingDetails } from './CardBillingDetails';
import {
    CardBillingDetailsFromJSON,
    CardBillingDetailsFromJSONTyped,
    CardBillingDetailsToJSON,
} from './CardBillingDetails';
import type { CardTokenInfo } from './CardTokenInfo';
import {
    CardTokenInfoFromJSON,
    CardTokenInfoFromJSONTyped,
    CardTokenInfoToJSON,
} from './CardTokenInfo';

/**
 * Card Token
 * @export
 * @interface CardToken
 */
export interface CardToken {
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    paymentMethodId: string;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    referenceId: string;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    status: CardTokenStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    redirectUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    maskedCardNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    expiryMonth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardToken
     */
    expiryYear?: string | null;
    /**
     * 
     * @type {CardTokenInfo}
     * @memberof CardToken
     */
    cardInfo?: CardTokenInfo | null;
    /**
     * 
     * @type {CardBillingDetails}
     * @memberof CardToken
     */
    billingDetails?: CardBillingDetails | null;
}


/**
 * @export
 */
export const CardTokenStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Expired: 'EXPIRED'
} as const;
export type CardTokenStatusEnum = typeof CardTokenStatusEnum[keyof typeof CardTokenStatusEnum];


/**
 * Check if a given object implements the CardToken interface.
 */
export function instanceOfCardToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "paymentMethodId" in value;
    isInstance = isInstance && "referenceId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function CardTokenFromJSON(json: any): CardToken {
    return CardTokenFromJSONTyped(json, false);
}

export function CardTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'paymentMethodId': json['payment_method_id'],
        'referenceId': json['reference_id'],
        'status': json['status'],
        'currency': json['currency'],
        'redirectUrl': !exists(json, 'redirect_url') ? undefined : json['redirect_url'],
        'maskedCardNumber': !exists(json, 'masked_card_number') ? undefined : json['masked_card_number'],
        'expiryMonth': !exists(json, 'expiry_month') ? undefined : json['expiry_month'],
        'expiryYear': !exists(json, 'expiry_year') ? undefined : json['expiry_year'],
        'cardInfo': !exists(json, 'card_info') ? undefined : CardTokenInfoFromJSON(json['card_info']),
        'billingDetails': !exists(json, 'billing_details') ? undefined : CardBillingDetailsFromJSON(json['billing_details']),
    };
}

export function CardTokenToJSON(value?: CardToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'payment_method_id': value.paymentMethodId,
        'reference_id': value.referenceId,
        'status': value.status,
        'currency': value.currency,
        'redirect_url': value.redirectUrl,
        'masked_card_number': value.maskedCardNumber,
        'expiry_month': value.expiryMonth,
        'expiry_year': value.expiryYear,
        'card_info': CardTokenInfoToJSON(value.cardInfo),
        'billing_details': CardBillingDetailsToJSON(value.billingDetails),
    };
}

