/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Card Token Info
 * @export
 * @interface CardTokenInfo
 */
export interface CardTokenInfo {
    /**
     * 
     * @type {string}
     * @memberof CardTokenInfo
     */
    bank?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTokenInfo
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTokenInfo
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTokenInfo
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTokenInfo
     */
    cardArtUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CardTokenInfo
     */
    fingerprint?: string;
}

/**
 * Check if a given object implements the CardTokenInfo interface.
 */
export function instanceOfCardTokenInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardTokenInfoFromJSON(json: any): CardTokenInfo {
    return CardTokenInfoFromJSONTyped(json, false);
}

export function CardTokenInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardTokenInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bank': !exists(json, 'bank') ? undefined : json['bank'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'cardArtUrl': !exists(json, 'card_art_url') ? undefined : json['card_art_url'],
        'fingerprint': !exists(json, 'fingerprint') ? undefined : json['fingerprint'],
    };
}

export function CardTokenInfoToJSON(value?: CardTokenInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bank': value.bank,
        'country': value.country,
        'type': value.type,
        'brand': value.brand,
        'card_art_url': value.cardArtUrl,
        'fingerprint': value.fingerprint,
    };
}

