/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { EwalletAccount } from './EwalletAccount';
import {
    EwalletAccountFromJSON,
    EwalletAccountFromJSONTyped,
    EwalletAccountToJSON,
} from './EwalletAccount';
import type { EwalletChannelCode } from './EwalletChannelCode';
import {
    EwalletChannelCodeFromJSON,
    EwalletChannelCodeFromJSONTyped,
    EwalletChannelCodeToJSON,
} from './EwalletChannelCode';
import type { EwalletChannelProperties } from './EwalletChannelProperties';
import {
    EwalletChannelPropertiesFromJSON,
    EwalletChannelPropertiesFromJSONTyped,
    EwalletChannelPropertiesToJSON,
} from './EwalletChannelProperties';

/**
 * 
 * @export
 * @interface MutableEwallet
 */
export interface MutableEwallet {
    /**
     * 
     * @type {EwalletChannelCode}
     * @memberof MutableEwallet
     */
    channelCode: EwalletChannelCode;
    /**
     * 
     * @type {EwalletChannelProperties}
     * @memberof MutableEwallet
     */
    channelProperties?: EwalletChannelProperties;
    /**
     * 
     * @type {EwalletAccount}
     * @memberof MutableEwallet
     */
    account?: EwalletAccount;
}

/**
 * Check if a given object implements the MutableEwallet interface.
 */
export function instanceOfMutableEwallet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;

    return isInstance;
}

export function MutableEwalletFromJSON(json: any): MutableEwallet {
    return MutableEwalletFromJSONTyped(json, false);
}

export function MutableEwalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutableEwallet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': EwalletChannelCodeFromJSON(json['channel_code']),
        'channelProperties': !exists(json, 'channel_properties') ? undefined : EwalletChannelPropertiesFromJSON(json['channel_properties']),
        'account': !exists(json, 'account') ? undefined : EwalletAccountFromJSON(json['account']),
    };
}

export function MutableEwalletToJSON(value?: MutableEwallet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': EwalletChannelCodeToJSON(value.channelCode),
        'channel_properties': EwalletChannelPropertiesToJSON(value.channelProperties),
        'account': EwalletAccountToJSON(value.account),
    };
}

