/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DirectDebitBankAccount } from './DirectDebitBankAccount';
import {
    DirectDebitBankAccountFromJSON,
    DirectDebitBankAccountFromJSONTyped,
    DirectDebitBankAccountToJSON,
} from './DirectDebitBankAccount';
import type { DirectDebitDebitCard } from './DirectDebitDebitCard';
import {
    DirectDebitDebitCardFromJSON,
    DirectDebitDebitCardFromJSONTyped,
    DirectDebitDebitCardToJSON,
} from './DirectDebitDebitCard';
import type { DirectDebitType } from './DirectDebitType';
import {
    DirectDebitTypeFromJSON,
    DirectDebitTypeFromJSONTyped,
    DirectDebitTypeToJSON,
} from './DirectDebitType';

/**
 * 
 * @export
 * @interface PublicDirectDebitAllOf
 */
export interface PublicDirectDebitAllOf {
    /**
     * 
     * @type {DirectDebitType}
     * @memberof PublicDirectDebitAllOf
     */
    type: DirectDebitType;
    /**
     * 
     * @type {DirectDebitBankAccount}
     * @memberof PublicDirectDebitAllOf
     */
    bankAccount?: DirectDebitBankAccount | null;
    /**
     * 
     * @type {DirectDebitDebitCard}
     * @memberof PublicDirectDebitAllOf
     */
    debitCard?: DirectDebitDebitCard | null;
}

/**
 * Check if a given object implements the PublicDirectDebitAllOf interface.
 */
export function instanceOfPublicDirectDebitAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PublicDirectDebitAllOfFromJSON(json: any): PublicDirectDebitAllOf {
    return PublicDirectDebitAllOfFromJSONTyped(json, false);
}

export function PublicDirectDebitAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicDirectDebitAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': DirectDebitTypeFromJSON(json['type']),
        'bankAccount': !exists(json, 'bank_account') ? undefined : DirectDebitBankAccountFromJSON(json['bank_account']),
        'debitCard': !exists(json, 'debit_card') ? undefined : DirectDebitDebitCardFromJSON(json['debit_card']),
    };
}

export function PublicDirectDebitAllOfToJSON(value?: PublicDirectDebitAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': DirectDebitTypeToJSON(value.type),
        'bank_account': DirectDebitBankAccountToJSON(value.bankAccount),
        'debit_card': DirectDebitDebitCardToJSON(value.debitCard),
    };
}

