/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicSimulatePaymentByPaymentMethodIdRequest
 */
export interface PublicSimulatePaymentByPaymentMethodIdRequest {
    /**
     * 
     * @type {number}
     * @memberof PublicSimulatePaymentByPaymentMethodIdRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the PublicSimulatePaymentByPaymentMethodIdRequest interface.
 */
export function instanceOfPublicSimulatePaymentByPaymentMethodIdRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublicSimulatePaymentByPaymentMethodIdRequestFromJSON(json: any): PublicSimulatePaymentByPaymentMethodIdRequest {
    return PublicSimulatePaymentByPaymentMethodIdRequestFromJSONTyped(json, false);
}

export function PublicSimulatePaymentByPaymentMethodIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSimulatePaymentByPaymentMethodIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function PublicSimulatePaymentByPaymentMethodIdRequestToJSON(value?: PublicSimulatePaymentByPaymentMethodIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
    };
}

