/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicAuthPaymentMethod
 */
export interface PublicAuthPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof PublicAuthPaymentMethod
     */
    authCode: string;
}

/**
 * Check if a given object implements the PublicAuthPaymentMethod interface.
 */
export function instanceOfPublicAuthPaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authCode" in value;

    return isInstance;
}

export function PublicAuthPaymentMethodFromJSON(json: any): PublicAuthPaymentMethod {
    return PublicAuthPaymentMethodFromJSONTyped(json, false);
}

export function PublicAuthPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAuthPaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authCode': json['auth_code'],
    };
}

export function PublicAuthPaymentMethodToJSON(value?: PublicAuthPaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth_code': value.authCode,
    };
}

