/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Direct Bank Transfer Channel Properties
 * @export
 * @interface DirectBankTransferChannelProperties
 */
export interface DirectBankTransferChannelProperties {
    /**
     * URL where the end-customer is redirected if the authorization is successful
     * @type {string}
     * @memberof DirectBankTransferChannelProperties
     */
    authorizedReturnUrl?: string;
    /**
     * URL where the end-customer is redirected if the authorization failed
     * @type {string}
     * @memberof DirectBankTransferChannelProperties
     */
    failureReturnUrl?: string;
}

/**
 * Check if a given object implements the DirectBankTransferChannelProperties interface.
 */
export function instanceOfDirectBankTransferChannelProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DirectBankTransferChannelPropertiesFromJSON(json: any): DirectBankTransferChannelProperties {
    return DirectBankTransferChannelPropertiesFromJSONTyped(json, false);
}

export function DirectBankTransferChannelPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectBankTransferChannelProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizedReturnUrl': !exists(json, 'authorized_return_url') ? undefined : json['authorized_return_url'],
        'failureReturnUrl': !exists(json, 'failure_return_url') ? undefined : json['failure_return_url'],
    };
}

export function DirectBankTransferChannelPropertiesToJSON(value?: DirectBankTransferChannelProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorized_return_url': value.authorizedReturnUrl,
        'failure_return_url': value.failureReturnUrl,
    };
}

