/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    method?: LinkMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    rel?: LinkRelEnum;
}


/**
 * @export
 */
export const LinkMethodEnum = {
    Get: 'GET'
} as const;
export type LinkMethodEnum = typeof LinkMethodEnum[keyof typeof LinkMethodEnum];

/**
 * @export
 */
export const LinkRelEnum = {
    First: 'first',
    Last: 'last',
    Next: 'next',
    Previous: 'previous'
} as const;
export type LinkRelEnum = typeof LinkRelEnum[keyof typeof LinkRelEnum];


/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LinkFromJSON(json: any): Link {
    return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Link {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'rel': !exists(json, 'rel') ? undefined : json['rel'],
    };
}

export function LinkToJSON(value?: Link | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'method': value.method,
        'rel': value.rel,
    };
}

