/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { PublicPaymentRequest } from './PublicPaymentRequest';
import {
    PublicPaymentRequestFromJSON,
    PublicPaymentRequestFromJSONTyped,
    PublicPaymentRequestToJSON,
} from './PublicPaymentRequest';

/**
 * 
 * @export
 * @interface PublicPaymentRequestListResponse
 */
export interface PublicPaymentRequestListResponse {
    /**
     * 
     * @type {Array<PublicPaymentRequest>}
     * @memberof PublicPaymentRequestListResponse
     */
    data: Array<PublicPaymentRequest>;
    /**
     * 
     * @type {boolean}
     * @memberof PublicPaymentRequestListResponse
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the PublicPaymentRequestListResponse interface.
 */
export function instanceOfPublicPaymentRequestListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "hasMore" in value;

    return isInstance;
}

export function PublicPaymentRequestListResponseFromJSON(json: any): PublicPaymentRequestListResponse {
    return PublicPaymentRequestListResponseFromJSONTyped(json, false);
}

export function PublicPaymentRequestListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPaymentRequestListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PublicPaymentRequestFromJSON)),
        'hasMore': json['has_more'],
    };
}

export function PublicPaymentRequestListResponseToJSON(value?: PublicPaymentRequestListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(PublicPaymentRequestToJSON)),
        'has_more': value.hasMore,
    };
}

