/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PublicPaymentRequestAuthorize
 */
export interface PublicPaymentRequestAuthorize {
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentRequestAuthorize
     */
    authCode: string;
}

/**
 * Check if a given object implements the PublicPaymentRequestAuthorize interface.
 */
export function instanceOfPublicPaymentRequestAuthorize(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authCode" in value;

    return isInstance;
}

export function PublicPaymentRequestAuthorizeFromJSON(json: any): PublicPaymentRequestAuthorize {
    return PublicPaymentRequestAuthorizeFromJSONTyped(json, false);
}

export function PublicPaymentRequestAuthorizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPaymentRequestAuthorize {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authCode': json['auth_code'],
    };
}

export function PublicPaymentRequestAuthorizeToJSON(value?: PublicPaymentRequestAuthorize | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth_code': value.authCode,
    };
}

