/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { InternalVirtualAccount } from './InternalVirtualAccount';
import {
    InternalVirtualAccountFromJSON,
    InternalVirtualAccountFromJSONTyped,
    InternalVirtualAccountToJSON,
} from './InternalVirtualAccount';
import type { MutableCard } from './MutableCard';
import {
    MutableCardFromJSON,
    MutableCardFromJSONTyped,
    MutableCardToJSON,
} from './MutableCard';
import type { MutableCrypto } from './MutableCrypto';
import {
    MutableCryptoFromJSON,
    MutableCryptoFromJSONTyped,
    MutableCryptoToJSON,
} from './MutableCrypto';
import type { MutableDirectBankTransfer } from './MutableDirectBankTransfer';
import {
    MutableDirectBankTransferFromJSON,
    MutableDirectBankTransferFromJSONTyped,
    MutableDirectBankTransferToJSON,
} from './MutableDirectBankTransfer';
import type { MutableDirectDebit } from './MutableDirectDebit';
import {
    MutableDirectDebitFromJSON,
    MutableDirectDebitFromJSONTyped,
    MutableDirectDebitToJSON,
} from './MutableDirectDebit';
import type { MutableEwallet } from './MutableEwallet';
import {
    MutableEwalletFromJSON,
    MutableEwalletFromJSONTyped,
    MutableEwalletToJSON,
} from './MutableEwallet';
import type { MutableOverTheCounter } from './MutableOverTheCounter';
import {
    MutableOverTheCounterFromJSON,
    MutableOverTheCounterFromJSONTyped,
    MutableOverTheCounterToJSON,
} from './MutableOverTheCounter';
import type { MutableQRCode } from './MutableQRCode';
import {
    MutableQRCodeFromJSON,
    MutableQRCodeFromJSONTyped,
    MutableQRCodeToJSON,
} from './MutableQRCode';
import type { PaymentMethodReusability } from './PaymentMethodReusability';
import {
    PaymentMethodReusabilityFromJSON,
    PaymentMethodReusabilityFromJSONTyped,
    PaymentMethodReusabilityToJSON,
} from './PaymentMethodReusability';
import type { PaymentMethodStatus } from './PaymentMethodStatus';
import {
    PaymentMethodStatusFromJSON,
    PaymentMethodStatusFromJSONTyped,
    PaymentMethodStatusToJSON,
} from './PaymentMethodStatus';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
} from './PaymentMethodType';

/**
 * 
 * @export
 * @interface PublicPaymentMethod
 */
export interface PublicPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    id: string;
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof PublicPaymentMethod
     */
    type: PaymentMethodType;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    referenceId?: string;
    /**
     * 
     * @type {MutableCard}
     * @memberof PublicPaymentMethod
     */
    card: MutableCard | null;
    /**
     * 
     * @type {MutableCrypto}
     * @memberof PublicPaymentMethod
     */
    cryptocurrency?: MutableCrypto | null;
    /**
     * 
     * @type {MutableDirectBankTransfer}
     * @memberof PublicPaymentMethod
     */
    directBankTransfer: MutableDirectBankTransfer | null;
    /**
     * 
     * @type {MutableDirectDebit}
     * @memberof PublicPaymentMethod
     */
    directDebit: MutableDirectDebit | null;
    /**
     * 
     * @type {MutableEwallet}
     * @memberof PublicPaymentMethod
     */
    ewallet: MutableEwallet | null;
    /**
     * 
     * @type {MutableOverTheCounter}
     * @memberof PublicPaymentMethod
     */
    overTheCounter: MutableOverTheCounter | null;
    /**
     * 
     * @type {InternalVirtualAccount}
     * @memberof PublicPaymentMethod
     */
    virtualAccount: InternalVirtualAccount | null;
    /**
     * 
     * @type {MutableQRCode}
     * @memberof PublicPaymentMethod
     */
    qrCode: MutableQRCode | null;
    /**
     * 
     * @type {PaymentMethodReusability}
     * @memberof PublicPaymentMethod
     */
    reusability: PaymentMethodReusability;
    /**
     * 
     * @type {PaymentMethodStatus}
     * @memberof PublicPaymentMethod
     */
    status: PaymentMethodStatus;
    /**
     * 
     * @type {object}
     * @memberof PublicPaymentMethod
     */
    metadata?: object | null;
}

/**
 * Check if a given object implements the PublicPaymentMethod interface.
 */
export function instanceOfPublicPaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "card" in value;
    isInstance = isInstance && "directBankTransfer" in value;
    isInstance = isInstance && "directDebit" in value;
    isInstance = isInstance && "ewallet" in value;
    isInstance = isInstance && "overTheCounter" in value;
    isInstance = isInstance && "virtualAccount" in value;
    isInstance = isInstance && "qrCode" in value;
    isInstance = isInstance && "reusability" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function PublicPaymentMethodFromJSON(json: any): PublicPaymentMethod {
    return PublicPaymentMethodFromJSONTyped(json, false);
}

export function PublicPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': PaymentMethodTypeFromJSON(json['type']),
        'created': !exists(json, 'created') ? undefined : json['created'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'card': MutableCardFromJSON(json['card']),
        'cryptocurrency': !exists(json, 'cryptocurrency') ? undefined : MutableCryptoFromJSON(json['cryptocurrency']),
        'directBankTransfer': MutableDirectBankTransferFromJSON(json['direct_bank_transfer']),
        'directDebit': MutableDirectDebitFromJSON(json['direct_debit']),
        'ewallet': MutableEwalletFromJSON(json['ewallet']),
        'overTheCounter': MutableOverTheCounterFromJSON(json['over_the_counter']),
        'virtualAccount': InternalVirtualAccountFromJSON(json['virtual_account']),
        'qrCode': MutableQRCodeFromJSON(json['qr_code']),
        'reusability': PaymentMethodReusabilityFromJSON(json['reusability']),
        'status': PaymentMethodStatusFromJSON(json['status']),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function PublicPaymentMethodToJSON(value?: PublicPaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': PaymentMethodTypeToJSON(value.type),
        'created': value.created,
        'updated': value.updated,
        'description': value.description,
        'reference_id': value.referenceId,
        'card': MutableCardToJSON(value.card),
        'cryptocurrency': MutableCryptoToJSON(value.cryptocurrency),
        'direct_bank_transfer': MutableDirectBankTransferToJSON(value.directBankTransfer),
        'direct_debit': MutableDirectDebitToJSON(value.directDebit),
        'ewallet': MutableEwalletToJSON(value.ewallet),
        'over_the_counter': MutableOverTheCounterToJSON(value.overTheCounter),
        'virtual_account': InternalVirtualAccountToJSON(value.virtualAccount),
        'qr_code': MutableQRCodeToJSON(value.qrCode),
        'reusability': PaymentMethodReusabilityToJSON(value.reusability),
        'status': PaymentMethodStatusToJSON(value.status),
        'metadata': value.metadata,
    };
}

