/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


import * as runtime from '../../runtime';
import type {
  ErrorResponse,
  ErrorV2Response,
  GetPayouts200Response,
  GetPayouts200ResponseDataInner,
  PayoutChannelV2,
  PayoutChannelV2CategoryRequest,
  PayoutV2Request,
} from '../models';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ErrorV2ResponseFromJSON,
    ErrorV2ResponseToJSON,
    GetPayouts200ResponseFromJSON,
    GetPayouts200ResponseToJSON,
    GetPayouts200ResponseDataInnerFromJSON,
    GetPayouts200ResponseDataInnerToJSON,
    PayoutChannelV2FromJSON,
    PayoutChannelV2ToJSON,
    PayoutChannelV2CategoryRequestFromJSON,
    PayoutChannelV2CategoryRequestToJSON,
    PayoutV2RequestFromJSON,
    PayoutV2RequestToJSON,
} from '../models';

export interface CancelPayoutRequest {
    id: string;
    idempotencyKey?: string;
}

export interface CreatePayoutRequest {
    idempotencyKey: string;
    forUserId?: string;
    payoutV2Request?: PayoutV2Request;
}

export interface GetPayoutByIdRequest {
    id: string;
    idempotencyKey?: string;
}

export interface GetPayoutChannelsRequest {
    currency?: string;
    channelCategory?: Array<PayoutChannelV2CategoryRequest>;
    channelCode?: string;
    idempotencyKey?: string;
}

export interface GetPayoutsRequest {
    referenceId: string;
    limit?: number;
    afterId?: string;
    beforeId?: string;
    idempotencyKey?: string;
}

/**
 * 
 */
export class PayoutsApi extends runtime.BaseAPI {

    secretKey: string;
    xenditURL: string;

    constructor({secretKey, xenditURL}: {secretKey: string, xenditURL?: string}) {
        super()
        this.secretKey = secretKey;
        this.xenditURL = xenditURL || 'https://api.xendit.co';
    }

    /**
     */
    private async cancelPayoutRaw(requestParameters: CancelPayoutRequest): Promise<runtime.ApiResponse<GetPayouts200ResponseDataInner>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling cancelPayout.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters["Authorization"] = "Basic " + btoa(this.secretKey + ":");

        if (requestParameters.idempotencyKey !== undefined && requestParameters.idempotencyKey !== null) {
            headerParameters['idempotency-key'] = String(requestParameters.idempotencyKey);
        }

        const response = await this.request({
            path: `/v2/payouts/{id}/cancel`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPayouts200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     */
    async cancelPayout(requestParameters: CancelPayoutRequest): Promise<GetPayouts200ResponseDataInner> {
        const response = await this.cancelPayoutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    private async createPayoutRaw(requestParameters: CreatePayoutRequest): Promise<runtime.ApiResponse<GetPayouts200ResponseDataInner>> {
        if (requestParameters.idempotencyKey === null || requestParameters.idempotencyKey === undefined) {
            throw new runtime.RequiredError('idempotencyKey','Required parameter requestParameters.idempotencyKey was null or undefined when calling createPayout.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters["Authorization"] = "Basic " + btoa(this.secretKey + ":");

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.idempotencyKey !== undefined && requestParameters.idempotencyKey !== null) {
            headerParameters['idempotency-key'] = String(requestParameters.idempotencyKey);
        }

        if (requestParameters.forUserId !== undefined && requestParameters.forUserId !== null) {
            headerParameters['for-user-id'] = String(requestParameters.forUserId);
        }

        const response = await this.request({
            path: `/v2/payouts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayoutV2RequestToJSON(requestParameters.payoutV2Request),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPayouts200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     */
    async createPayout(requestParameters: CreatePayoutRequest): Promise<GetPayouts200ResponseDataInner> {
        const response = await this.createPayoutRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    private async getPayoutByIdRaw(requestParameters: GetPayoutByIdRequest): Promise<runtime.ApiResponse<GetPayouts200ResponseDataInner>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getPayoutById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters["Authorization"] = "Basic " + btoa(this.secretKey + ":");

        if (requestParameters.idempotencyKey !== undefined && requestParameters.idempotencyKey !== null) {
            headerParameters['idempotency-key'] = String(requestParameters.idempotencyKey);
        }

        const response = await this.request({
            path: `/v2/payouts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPayouts200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     */
    async getPayoutById(requestParameters: GetPayoutByIdRequest): Promise<GetPayouts200ResponseDataInner> {
        const response = await this.getPayoutByIdRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    private async getPayoutChannelsRaw(requestParameters: GetPayoutChannelsRequest): Promise<runtime.ApiResponse<Array<PayoutChannelV2>>> {
        const queryParameters: any = {};

        if (requestParameters.currency !== undefined) {
            queryParameters['currency'] = requestParameters.currency;
        }

        if (requestParameters.channelCategory) {
            queryParameters['channel_category'] = requestParameters.channelCategory.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.channelCode !== undefined) {
            queryParameters['channel_code'] = requestParameters.channelCode;
        }

        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters["Authorization"] = "Basic " + btoa(this.secretKey + ":");

        if (requestParameters.idempotencyKey !== undefined && requestParameters.idempotencyKey !== null) {
            headerParameters['idempotency-key'] = String(requestParameters.idempotencyKey);
        }

        const response = await this.request({
            path: `/payouts_channels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PayoutChannelV2FromJSON));
    }

    /**
     */
    async getPayoutChannels(requestParameters: GetPayoutChannelsRequest = {}): Promise<Array<PayoutChannelV2>> {
        const response = await this.getPayoutChannelsRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    private async getPayoutsRaw(requestParameters: GetPayoutsRequest): Promise<runtime.ApiResponse<GetPayouts200Response>> {
        if (requestParameters.referenceId === null || requestParameters.referenceId === undefined) {
            throw new runtime.RequiredError('referenceId','Required parameter requestParameters.referenceId was null or undefined when calling getPayouts.');
        }

        const queryParameters: any = {};

        if (requestParameters.referenceId !== undefined) {
            queryParameters['reference_id'] = requestParameters.referenceId;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.afterId !== undefined) {
            queryParameters['after_id'] = requestParameters.afterId;
        }

        if (requestParameters.beforeId !== undefined) {
            queryParameters['before_id'] = requestParameters.beforeId;
        }

        const headerParameters: runtime.HTTPHeaders = {};
        headerParameters["Authorization"] = "Basic " + btoa(this.secretKey + ":");

        if (requestParameters.idempotencyKey !== undefined && requestParameters.idempotencyKey !== null) {
            headerParameters['idempotency-key'] = String(requestParameters.idempotencyKey);
        }

        const response = await this.request({
            path: `/v2/payouts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPayouts200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getPayouts(requestParameters: GetPayoutsRequest): Promise<GetPayouts200Response> {
        const response = await this.getPayoutsRaw(requestParameters);
        return await response.value();
    }

}
