/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface RefundsPostDefaultResponse
 */
export interface RefundsPostDefaultResponse {
    /**
     * 
     * @type {string}
     * @memberof RefundsPostDefaultResponse
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RefundsPostDefaultResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the RefundsPostDefaultResponse interface.
 */
export function instanceOfRefundsPostDefaultResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefundsPostDefaultResponseFromJSON(json: any): RefundsPostDefaultResponse {
    return RefundsPostDefaultResponseFromJSONTyped(json, false);
}

export function RefundsPostDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundsPostDefaultResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function RefundsPostDefaultResponseToJSON(value?: RefundsPostDefaultResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

