/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface RefundsPost400Response
 */
export interface RefundsPost400Response {
    /**
     * 
     * @type {string}
     * @memberof RefundsPost400Response
     */
    errorCode?: RefundsPost400ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof RefundsPost400Response
     */
    message?: string;
}


/**
 * @export
 */
export const RefundsPost400ResponseErrorCodeEnum = {
    ApiValidationError: 'API_VALIDATION_ERROR',
    IneligibleTransaction: 'INELIGIBLE_TRANSACTION',
    InsufficientBalance: 'INSUFFICIENT_BALANCE',
    MaximumRefundAmountReached: 'MAXIMUM_REFUND_AMOUNT_REACHED',
    PartialRefundNotSupported: 'PARTIAL_REFUND_NOT_SUPPORTED',
    RefundNotSupported: 'REFUND_NOT_SUPPORTED',
    TransactionNotFound: 'TRANSACTION_NOT_FOUND'
} as const;
export type RefundsPost400ResponseErrorCodeEnum = typeof RefundsPost400ResponseErrorCodeEnum[keyof typeof RefundsPost400ResponseErrorCodeEnum];


/**
 * Check if a given object implements the RefundsPost400Response interface.
 */
export function instanceOfRefundsPost400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefundsPost400ResponseFromJSON(json: any): RefundsPost400Response {
    return RefundsPost400ResponseFromJSONTyped(json, false);
}

export function RefundsPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundsPost400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function RefundsPost400ResponseToJSON(value?: RefundsPost400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

