/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface RefundsPost409Response
 */
export interface RefundsPost409Response {
    /**
     * 
     * @type {string}
     * @memberof RefundsPost409Response
     */
    errorCode?: RefundsPost409ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof RefundsPost409Response
     */
    message?: string;
}


/**
 * @export
 */
export const RefundsPost409ResponseErrorCodeEnum = {
    IdempotencyError: 'IDEMPOTENCY_ERROR'
} as const;
export type RefundsPost409ResponseErrorCodeEnum = typeof RefundsPost409ResponseErrorCodeEnum[keyof typeof RefundsPost409ResponseErrorCodeEnum];


/**
 * Check if a given object implements the RefundsPost409Response interface.
 */
export function instanceOfRefundsPost409Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefundsPost409ResponseFromJSON(json: any): RefundsPost409Response {
    return RefundsPost409ResponseFromJSONTyped(json, false);
}

export function RefundsPost409ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundsPost409Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function RefundsPost409ResponseToJSON(value?: RefundsPost409Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

