/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface CreateCapture
 */
export interface CreateCapture {
    /**
     * 
     * @type {string}
     * @memberof CreateCapture
     */
    referenceId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCapture
     */
    captureAmount: number;
}

/**
 * Check if a given object implements the CreateCapture interface.
 */
export function instanceOfCreateCapture(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "captureAmount" in value;

    return isInstance;
}

export function CreateCaptureFromJSON(json: any): CreateCapture {
    return CreateCaptureFromJSONTyped(json, false);
}

export function CreateCaptureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCapture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'captureAmount': json['capture_amount'],
    };
}

export function CreateCaptureToJSON(value?: CreateCapture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reference_id': value.referenceId,
        'capture_amount': value.captureAmount,
    };
}

