/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { OverTheCounterChannelCode } from './OverTheCounterChannelCode';
import {
    OverTheCounterChannelCodeFromJSON,
    OverTheCounterChannelCodeFromJSONTyped,
    OverTheCounterChannelCodeToJSON,
} from './OverTheCounterChannelCode';
import type { OverTheCounterChannelProperties } from './OverTheCounterChannelProperties';
import {
    OverTheCounterChannelPropertiesFromJSON,
    OverTheCounterChannelPropertiesFromJSONTyped,
    OverTheCounterChannelPropertiesToJSON,
} from './OverTheCounterChannelProperties';
import type { PaymentRequestCurrency } from './PaymentRequestCurrency';
import {
    PaymentRequestCurrencyFromJSON,
    PaymentRequestCurrencyFromJSONTyped,
    PaymentRequestCurrencyToJSON,
} from './PaymentRequestCurrency';

/**
 * 
 * @export
 * @interface MutableOverTheCounter
 */
export interface MutableOverTheCounter {
    /**
     * 
     * @type {number}
     * @memberof MutableOverTheCounter
     */
    amount?: number | null;
    /**
     * 
     * @type {PaymentRequestCurrency}
     * @memberof MutableOverTheCounter
     */
    currency?: PaymentRequestCurrency;
    /**
     * 
     * @type {OverTheCounterChannelCode}
     * @memberof MutableOverTheCounter
     */
    channelCode: OverTheCounterChannelCode;
    /**
     * 
     * @type {OverTheCounterChannelProperties}
     * @memberof MutableOverTheCounter
     */
    channelProperties: OverTheCounterChannelProperties;
}

/**
 * Check if a given object implements the MutableOverTheCounter interface.
 */
export function instanceOfMutableOverTheCounter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function MutableOverTheCounterFromJSON(json: any): MutableOverTheCounter {
    return MutableOverTheCounterFromJSONTyped(json, false);
}

export function MutableOverTheCounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutableOverTheCounter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : PaymentRequestCurrencyFromJSON(json['currency']),
        'channelCode': OverTheCounterChannelCodeFromJSON(json['channel_code']),
        'channelProperties': OverTheCounterChannelPropertiesFromJSON(json['channel_properties']),
    };
}

export function MutableOverTheCounterToJSON(value?: MutableOverTheCounter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': PaymentRequestCurrencyToJSON(value.currency),
        'channel_code': OverTheCounterChannelCodeToJSON(value.channelCode),
        'channel_properties': OverTheCounterChannelPropertiesToJSON(value.channelProperties),
    };
}

