/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const PayoutChannelV2CategoryRequest = {
    Bank: 'BANK',
    Ewallet: 'EWALLET',
    Otc: 'OTC'
} as const;
export type PayoutChannelV2CategoryRequest = typeof PayoutChannelV2CategoryRequest[keyof typeof PayoutChannelV2CategoryRequest];


export function PayoutChannelV2CategoryRequestFromJSON(json: any): PayoutChannelV2CategoryRequest {
    return PayoutChannelV2CategoryRequestFromJSONTyped(json, false);
}

export function PayoutChannelV2CategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayoutChannelV2CategoryRequest {
    return json as PayoutChannelV2CategoryRequest;
}

export function PayoutChannelV2CategoryRequestToJSON(value?: PayoutChannelV2CategoryRequest | null): any {
    return value as any;
}

