/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { MutableCard } from './MutableCard';
import {
    MutableCardFromJSON,
    MutableCardFromJSONTyped,
    MutableCardToJSON,
} from './MutableCard';
import type { MutableDirectDebit } from './MutableDirectDebit';
import {
    MutableDirectDebitFromJSON,
    MutableDirectDebitFromJSONTyped,
    MutableDirectDebitToJSON,
} from './MutableDirectDebit';
import type { MutableEwallet } from './MutableEwallet';
import {
    MutableEwalletFromJSON,
    MutableEwalletFromJSONTyped,
    MutableEwalletToJSON,
} from './MutableEwallet';
import type { MutableOverTheCounter } from './MutableOverTheCounter';
import {
    MutableOverTheCounterFromJSON,
    MutableOverTheCounterFromJSONTyped,
    MutableOverTheCounterToJSON,
} from './MutableOverTheCounter';
import type { MutableQRCode } from './MutableQRCode';
import {
    MutableQRCodeFromJSON,
    MutableQRCodeFromJSONTyped,
    MutableQRCodeToJSON,
} from './MutableQRCode';
import type { PaymentMethodReusability } from './PaymentMethodReusability';
import {
    PaymentMethodReusabilityFromJSON,
    PaymentMethodReusabilityFromJSONTyped,
    PaymentMethodReusabilityToJSON,
} from './PaymentMethodReusability';
import type { PaymentMethodStatus } from './PaymentMethodStatus';
import {
    PaymentMethodStatusFromJSON,
    PaymentMethodStatusFromJSONTyped,
    PaymentMethodStatusToJSON,
} from './PaymentMethodStatus';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
} from './PaymentMethodType';
import type { PublicVirtualAccount } from './PublicVirtualAccount';
import {
    PublicVirtualAccountFromJSON,
    PublicVirtualAccountFromJSONTyped,
    PublicVirtualAccountToJSON,
} from './PublicVirtualAccount';

/**
 * 
 * @export
 * @interface PublicPaymentMethod
 */
export interface PublicPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    id: string;
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof PublicPaymentMethod
     */
    type: PaymentMethodType;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicPaymentMethod
     */
    referenceId?: string;
    /**
     * 
     * @type {MutableCard}
     * @memberof PublicPaymentMethod
     */
    card?: MutableCard | null;
    /**
     * 
     * @type {MutableDirectDebit}
     * @memberof PublicPaymentMethod
     */
    directDebit?: MutableDirectDebit | null;
    /**
     * 
     * @type {MutableEwallet}
     * @memberof PublicPaymentMethod
     */
    ewallet?: MutableEwallet | null;
    /**
     * 
     * @type {MutableOverTheCounter}
     * @memberof PublicPaymentMethod
     */
    overTheCounter?: MutableOverTheCounter | null;
    /**
     * 
     * @type {PublicVirtualAccount}
     * @memberof PublicPaymentMethod
     */
    virtualAccount?: PublicVirtualAccount | null;
    /**
     * 
     * @type {MutableQRCode}
     * @memberof PublicPaymentMethod
     */
    qrCode?: MutableQRCode | null;
    /**
     * 
     * @type {PaymentMethodReusability}
     * @memberof PublicPaymentMethod
     */
    reusability: PaymentMethodReusability;
    /**
     * 
     * @type {PaymentMethodStatus}
     * @memberof PublicPaymentMethod
     */
    status: PaymentMethodStatus;
    /**
     * 
     * @type {object}
     * @memberof PublicPaymentMethod
     */
    metadata?: object | null;
}

/**
 * Check if a given object implements the PublicPaymentMethod interface.
 */
export function instanceOfPublicPaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "reusability" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function PublicPaymentMethodFromJSON(json: any): PublicPaymentMethod {
    return PublicPaymentMethodFromJSONTyped(json, false);
}

export function PublicPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': PaymentMethodTypeFromJSON(json['type']),
        'created': !exists(json, 'created') ? undefined : json['created'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'card': !exists(json, 'card') ? undefined : MutableCardFromJSON(json['card']),
        'directDebit': !exists(json, 'direct_debit') ? undefined : MutableDirectDebitFromJSON(json['direct_debit']),
        'ewallet': !exists(json, 'ewallet') ? undefined : MutableEwalletFromJSON(json['ewallet']),
        'overTheCounter': !exists(json, 'over_the_counter') ? undefined : MutableOverTheCounterFromJSON(json['over_the_counter']),
        'virtualAccount': !exists(json, 'virtual_account') ? undefined : PublicVirtualAccountFromJSON(json['virtual_account']),
        'qrCode': !exists(json, 'qr_code') ? undefined : MutableQRCodeFromJSON(json['qr_code']),
        'reusability': PaymentMethodReusabilityFromJSON(json['reusability']),
        'status': PaymentMethodStatusFromJSON(json['status']),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function PublicPaymentMethodToJSON(value?: PublicPaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': PaymentMethodTypeToJSON(value.type),
        'created': value.created,
        'updated': value.updated,
        'description': value.description,
        'reference_id': value.referenceId,
        'card': MutableCardToJSON(value.card),
        'direct_debit': MutableDirectDebitToJSON(value.directDebit),
        'ewallet': MutableEwalletToJSON(value.ewallet),
        'over_the_counter': MutableOverTheCounterToJSON(value.overTheCounter),
        'virtual_account': PublicVirtualAccountToJSON(value.virtualAccount),
        'qr_code': MutableQRCodeToJSON(value.qrCode),
        'reusability': PaymentMethodReusabilityToJSON(value.reusability),
        'status': PaymentMethodStatusToJSON(value.status),
        'metadata': value.metadata,
    };
}

