/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Cryptocurrency Channel Properties
 * @export
 * @interface CryptoChannelProperties
 */
export interface CryptoChannelProperties {
    /**
     * URL where the end-customer is redirected if the authorization is successful
     * @type {string}
     * @memberof CryptoChannelProperties
     */
    successReturnUrl?: string | null;
    /**
     * URL where the end-customer is redirected if the authorization failed
     * @type {string}
     * @memberof CryptoChannelProperties
     */
    failureReturnUrl?: string | null;
    /**
     * URL where the end-customer is redirected if the authorization cancelled
     * @type {string}
     * @memberof CryptoChannelProperties
     */
    cancelReturnUrl?: string | null;
}

/**
 * Check if a given object implements the CryptoChannelProperties interface.
 */
export function instanceOfCryptoChannelProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CryptoChannelPropertiesFromJSON(json: any): CryptoChannelProperties {
    return CryptoChannelPropertiesFromJSONTyped(json, false);
}

export function CryptoChannelPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoChannelProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'successReturnUrl': !exists(json, 'success_return_url') ? undefined : json['success_return_url'],
        'failureReturnUrl': !exists(json, 'failure_return_url') ? undefined : json['failure_return_url'],
        'cancelReturnUrl': !exists(json, 'cancel_return_url') ? undefined : json['cancel_return_url'],
    };
}

export function CryptoChannelPropertiesToJSON(value?: CryptoChannelProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success_return_url': value.successReturnUrl,
        'failure_return_url': value.failureReturnUrl,
        'cancel_return_url': value.cancelReturnUrl,
    };
}

