/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Cryptocurrency Channel Code
 * @export
 */
export const CryptoChannelCode = {
    Btc: 'BTC',
    Eth: 'ETH',
    Usdc: 'USDC'
} as const;
export type CryptoChannelCode = typeof CryptoChannelCode[keyof typeof CryptoChannelCode];


export function CryptoChannelCodeFromJSON(json: any): CryptoChannelCode {
    return CryptoChannelCodeFromJSONTyped(json, false);
}

export function CryptoChannelCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoChannelCode {
    return json as CryptoChannelCode;
}

export function CryptoChannelCodeToJSON(value?: CryptoChannelCode | null): any {
    return value as any;
}

