/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Direct Bank Transfer Channel Code
 * @export
 */
export const DirectBankTransferChannelCode = {
    Bdo: 'DP_BDO',
    Mbt: 'DP_MBT'
} as const;
export type DirectBankTransferChannelCode = typeof DirectBankTransferChannelCode[keyof typeof DirectBankTransferChannelCode];


export function DirectBankTransferChannelCodeFromJSON(json: any): DirectBankTransferChannelCode {
    return DirectBankTransferChannelCodeFromJSONTyped(json, false);
}

export function DirectBankTransferChannelCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectBankTransferChannelCode {
    return json as DirectBankTransferChannelCode;
}

export function DirectBankTransferChannelCodeToJSON(value?: DirectBankTransferChannelCode | null): any {
    return value as any;
}

