/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { PaymentRequestCurrency } from './PaymentRequestCurrency';
import {
    PaymentRequestCurrencyFromJSON,
    PaymentRequestCurrencyFromJSONTyped,
    PaymentRequestCurrencyToJSON,
} from './PaymentRequestCurrency';
import type { VirtualAccountChannelCode } from './VirtualAccountChannelCode';
import {
    VirtualAccountChannelCodeFromJSON,
    VirtualAccountChannelCodeFromJSONTyped,
    VirtualAccountChannelCodeToJSON,
} from './VirtualAccountChannelCode';
import type { VirtualAccountChannelProperties } from './VirtualAccountChannelProperties';
import {
    VirtualAccountChannelPropertiesFromJSON,
    VirtualAccountChannelPropertiesFromJSONTyped,
    VirtualAccountChannelPropertiesToJSON,
} from './VirtualAccountChannelProperties';

/**
 * 
 * @export
 * @interface MutableVirtualAccount
 */
export interface MutableVirtualAccount {
    /**
     * 
     * @type {number}
     * @memberof MutableVirtualAccount
     */
    minAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MutableVirtualAccount
     */
    maxAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MutableVirtualAccount
     */
    amount?: number | null;
    /**
     * 
     * @type {PaymentRequestCurrency}
     * @memberof MutableVirtualAccount
     */
    currency?: PaymentRequestCurrency;
    /**
     * 
     * @type {VirtualAccountChannelCode}
     * @memberof MutableVirtualAccount
     */
    channelCode: VirtualAccountChannelCode;
    /**
     * 
     * @type {VirtualAccountChannelProperties}
     * @memberof MutableVirtualAccount
     */
    channelProperties: VirtualAccountChannelProperties;
    /**
     * Alternative display requested for the virtual account
     * @type {Array<string>}
     * @memberof MutableVirtualAccount
     */
    alternativeDisplayTypes?: Array<MutableVirtualAccountAlternativeDisplayTypesEnum>;
}


/**
 * @export
 */
export const MutableVirtualAccountAlternativeDisplayTypesEnum = {
    QrString: 'QR_STRING'
} as const;
export type MutableVirtualAccountAlternativeDisplayTypesEnum = typeof MutableVirtualAccountAlternativeDisplayTypesEnum[keyof typeof MutableVirtualAccountAlternativeDisplayTypesEnum];


/**
 * Check if a given object implements the MutableVirtualAccount interface.
 */
export function instanceOfMutableVirtualAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function MutableVirtualAccountFromJSON(json: any): MutableVirtualAccount {
    return MutableVirtualAccountFromJSONTyped(json, false);
}

export function MutableVirtualAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutableVirtualAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minAmount': !exists(json, 'min_amount') ? undefined : json['min_amount'],
        'maxAmount': !exists(json, 'max_amount') ? undefined : json['max_amount'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : PaymentRequestCurrencyFromJSON(json['currency']),
        'channelCode': VirtualAccountChannelCodeFromJSON(json['channel_code']),
        'channelProperties': VirtualAccountChannelPropertiesFromJSON(json['channel_properties']),
        'alternativeDisplayTypes': !exists(json, 'alternative_display_types') ? undefined : json['alternative_display_types'],
    };
}

export function MutableVirtualAccountToJSON(value?: MutableVirtualAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'min_amount': value.minAmount,
        'max_amount': value.maxAmount,
        'amount': value.amount,
        'currency': PaymentRequestCurrencyToJSON(value.currency),
        'channel_code': VirtualAccountChannelCodeToJSON(value.channelCode),
        'channel_properties': VirtualAccountChannelPropertiesToJSON(value.channelProperties),
        'alternative_display_types': value.alternativeDisplayTypes,
    };
}

