/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DirectBankTransferChannelCode } from './DirectBankTransferChannelCode';
import {
    DirectBankTransferChannelCodeFromJSON,
    DirectBankTransferChannelCodeFromJSONTyped,
    DirectBankTransferChannelCodeToJSON,
} from './DirectBankTransferChannelCode';
import type { DirectBankTransferChannelProperties } from './DirectBankTransferChannelProperties';
import {
    DirectBankTransferChannelPropertiesFromJSON,
    DirectBankTransferChannelPropertiesFromJSONTyped,
    DirectBankTransferChannelPropertiesToJSON,
} from './DirectBankTransferChannelProperties';

/**
 * 
 * @export
 * @interface MutableDirectBankTransfer
 */
export interface MutableDirectBankTransfer {
    /**
     * 
     * @type {DirectBankTransferChannelCode}
     * @memberof MutableDirectBankTransfer
     */
    channelCode?: DirectBankTransferChannelCode;
    /**
     * 
     * @type {DirectBankTransferChannelProperties}
     * @memberof MutableDirectBankTransfer
     */
    channelProperties?: DirectBankTransferChannelProperties;
}

/**
 * Check if a given object implements the MutableDirectBankTransfer interface.
 */
export function instanceOfMutableDirectBankTransfer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MutableDirectBankTransferFromJSON(json: any): MutableDirectBankTransfer {
    return MutableDirectBankTransferFromJSONTyped(json, false);
}

export function MutableDirectBankTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutableDirectBankTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': !exists(json, 'channel_code') ? undefined : DirectBankTransferChannelCodeFromJSON(json['channel_code']),
        'channelProperties': !exists(json, 'channel_properties') ? undefined : DirectBankTransferChannelPropertiesFromJSON(json['channel_properties']),
    };
}

export function MutableDirectBankTransferToJSON(value?: MutableDirectBankTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': DirectBankTransferChannelCodeToJSON(value.channelCode),
        'channel_properties': DirectBankTransferChannelPropertiesToJSON(value.channelProperties),
    };
}

