/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardChannelProperties } from './CardChannelProperties';
import {
    CardChannelPropertiesFromJSON,
    CardChannelPropertiesFromJSONTyped,
    CardChannelPropertiesToJSON,
} from './CardChannelProperties';
import type { CardInformation } from './CardInformation';
import {
    CardInformationFromJSON,
    CardInformationFromJSONTyped,
    CardInformationToJSON,
} from './CardInformation';
import type { CardVerificationResults } from './CardVerificationResults';
import {
    CardVerificationResultsFromJSON,
    CardVerificationResultsFromJSONTyped,
    CardVerificationResultsToJSON,
} from './CardVerificationResults';

/**
 * 
 * @export
 * @interface MutableCard
 */
export interface MutableCard {
    /**
     * 
     * @type {CardChannelProperties}
     * @memberof MutableCard
     */
    channelProperties?: CardChannelProperties;
    /**
     * 
     * @type {CardInformation}
     * @memberof MutableCard
     */
    cardInformation?: CardInformation;
    /**
     * 
     * @type {CardVerificationResults}
     * @memberof MutableCard
     */
    cardVerificationResults?: CardVerificationResults | null;
}

/**
 * Check if a given object implements the MutableCard interface.
 */
export function instanceOfMutableCard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MutableCardFromJSON(json: any): MutableCard {
    return MutableCardFromJSONTyped(json, false);
}

export function MutableCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutableCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelProperties': !exists(json, 'channel_properties') ? undefined : CardChannelPropertiesFromJSON(json['channel_properties']),
        'cardInformation': !exists(json, 'card_information') ? undefined : CardInformationFromJSON(json['card_information']),
        'cardVerificationResults': !exists(json, 'card_verification_results') ? undefined : CardVerificationResultsFromJSON(json['card_verification_results']),
    };
}

export function MutableCardToJSON(value?: MutableCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_properties': CardChannelPropertiesToJSON(value.channelProperties),
        'card_information': CardInformationToJSON(value.cardInformation),
        'card_verification_results': CardVerificationResultsToJSON(value.cardVerificationResults),
    };
}

